### ISSUE TITLE
`classCallCheck` is included even though its not used

### ISSUE THREAD

**Issue by Swatinem** [rollup/rollup-plugin-babel#1]
The following snipped is included in the final bundle, even though it is not used in the bundled code at all:

```js
  var babelHelpers = {};

  babelHelpers.classCallCheck = function (instance, Constructor) {
    if (!(instance instanceof Constructor)) {
      throw new TypeError("Cannot call a class as a function");
    }
  };
```

**Comment by Rich-Harris** [comment]
Ah, interesting. Do you have a class somewhere in your code that is being stripped out? Hadn't considered that case. Do you have a repro I can take a poke at?

**Comment by Swatinem** [comment]
Sorry, its closed source.

I actually build two different entry files with gobble-rollup, one has a class, the other does not. I share the same plugin "instance" for both. Probably thats the problem, I will try to initialize it fresh for both calls.

**Comment by Swatinem** [comment]
Ok yes that was indeed the problem. Sorry for the inconvenience.

But now that file (without the class) generates an empty sourcemap when run through uglify, but that is probably an uglify problem.
