### ISSUE TITLE
sourcemap option doesn't seem to work

### ISSUE THREAD

**Issue by vdclouis** [rollup/rollup-plugin-babel#10]
npm modules:
```json
"devDependencies": {
    "autoprefixer": "^6.1.0",
    "babel-preset-es2015-rollup": "^1.0.0",
    "browser-sync": "^2.9.12",
    "clean-css": "^3.4.8",
    "eslint": "^1.9.0",
    "hashmark": "^3.0.0",
    "jade": "^1.11.0",
    "node-sass": "^3.4.2",
    "postcss-cli": "^2.3.2",
    "rollup": "^0.21.0",
    "rollup-plugin-babel": "^2.0.1",
    "uglify-js": "^2.6.0"
  }
```

rollup config:
```js
import babel from 'rollup-plugin-babel';

export default {
    entry: 'src/app.js',
    dest: 'dist/app.js',
    plugins: [
        babel({
            sourceMaps: 'both' 
        })
    ]
}
```

2 things. The `README` in this repo mentions `sourceMap` as an option. But the babel docs are talking about `sourceMaps` (with an s). But either way I can't make sourcemaps work for some reason (tried both `true` and `'both'`)
any ideas?

**Comment by Victorystick** [comment]
The option for this plugin is called `sourceMap`, so that's what you should use. (I've no idea what `both` means.) Also, note that the latest version (`2.1.0`) generates source maps per default.

```js
import babel from 'rollup-plugin-babel';

export default {
    entry: 'src/app.js',
    dest: 'dist/app.js',
    plugins: [
        babel({
            sourceMap: true // redundant
        })
    ]
}
```

**Comment by Rich-Harris** [comment]
Sorry for the long delay. The Rollup config itself needs the `sourceMap` option. This plugin [assumes you want sourcemaps unless you say otherwise](https://github.com/rollup/rollup-plugin-babel/blob/9778c9bcaab5e3e77569c343ffe95304fb957de0/index.js#L20-L21). So your config should look like this:

```js
import babel from 'rollup-plugin-babel';

export default {
    entry: 'src/app.js',
    dest: 'dist/app.js',
    plugins: [
        babel()
    ],
    sourceMap: true
}
```

Reopen if that doesn't work!
