### ISSUE TITLE
Unable to exclude imports from being transpiled by babel

### ISSUE THREAD

**Issue by matt3224** [rollup/rollup-plugin-babel#101]
Hi,

Is there any way for me to tell babel to ignore certain imports, for example i don't want babel to touch any es5 imports like polyfills.

I have tried the exclude option but it doesn't do anything. Here are my dev dependancies:
```json
"devDependencies": {
    "babel-preset-es2015-rollup": "^1.2.0",
    "rollup": "^0.36.3",
    "rollup-plugin-babel": "^2.6.1"
}
```

Also here is my index.js with comments showing what I want babel to ignore:
```Javascript
/* BABEL DON"T TOUCH THESE PLEASE */
import "parties/promise.js";
import "parties/fetch.js";
import "parties/domtastic.min.js";
/* END BABEL NO TOUCHY */



/* BABEL TRANSPILE THESE */
import "settings/global.js";   
import "settings/tabs.js";
import "modules/helpers.js";
import "modules/modal.js";
import "modules/notify.js";
import "modules/tabs.js";
/* END BABEL TRANSPILE */
```

How can I do this? Do I need another package to deal with this?

Any help much appreciated, thanks.

**Comment by Rich-Harris** [comment]
Can you share your config file? A setting like `exclude: [ 'parties/*.js' ]` *should* exclude those files.

**Comment by matt3224** [comment]
Thanks Rich, I did manage to solve this in the end 👍
