### ISSUE TITLE
Incorrect algorithm in `preflightCheck`

### ISSUE THREAD

**Issue by demiazz** [rollup/rollup-plugin-babel#102]
Function `preflightCheck` ignore babel options as `ignore` or `only`.

If I ignore `node_modules` directory, and try compile code, plugin throw error on any file inside `node_modules` (in my case, I use `rollup` with `karma`, and have errors in `deep-equal` or `jquery`).

If the function uses current way for helpers existing, then the function must check file path with using `only`/ignore` options.

**Comment by Rich-Harris** [comment]
Shuold be fixed in 2.7.1 – thanks
