### ISSUE TITLE
How can I pass in args and make assignments when using the iife format?

### ISSUE THREAD

**Issue by matt3224** [rollup/rollup-plugin-babel#104]
Hey,

I would like rollup to produce my top level iife like this:
```Javascript
(function (UIKit) {

    'use strict'

    /* all my modules */

})(window.UIKit = window.UIKit || {});
```

I cannot workout how to do this and i'm sure it's simple.

Thank you!

**Comment by matt3224** [comment]
Also here is my `main.js` which will go inside the iife top-level wrapper

```
import './parties/promise';
import './parties/fetch';
import './parties/domtastic';

import './settings/global';   
import './settings/tabs';

import './modules/helpers';
import './modules/modal';
import './modules/notify';
import './modules/tabs';
```

**Comment by Rich-Harris** [comment]
[Like this?](http://rollupjs.org/?version=0.37.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJy4lMkZvdGhlci5qcyclM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwZm9vJTIwJTNEJTIwMSUzQiU1Q25leHBvcnQlMjBjb25zdCUyMGJhciUyMCUzRCUyMDIlM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyb3RoZXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc29sZS5sb2coJTIwJ2hlcmUnJTIwKSUzQiUyMiU3RCU1RCU3RA==) You just need to set `format: 'iife'` when creating your bundle.

I'm going to close this issue as it doesn't relate to rollup-plugin-babel – reopen on the [main repo](https://github.com/rollup/rollup/issues) if you're still having problems. Thanks!
