### ISSUE TITLE
Respect Rollup `onwarn`

### ISSUE THREAD

**Issue by ryaninvents** [rollup/rollup-plugin-babel#110]
I'm using Rollup in a Gulp task and have set `onwarn: (message) => gutil.log('%s: %s', gutil.colors.red(rollup), message)` in my Rollup config. However, `rollup-plugin-babel` disregards this setting and directly uses `console.log`.

I see that there's [some code](https://github.com/rollup/rollup-plugin-babel/blob/master/src/index.js#L39) that seems to pull the passed `onwarn` method, but I haven't been able to get this to work.

**Comment by Andarist** [comment]
We have some tests for passing ur own `onwarn` function and it seems to be working. Maybe it's something specific about ur setup with gulp? Without having a full repro case I cannot investigate this any further.
