### ISSUE TITLE
Default to only including .es6, .es, .jsx and .js extensions

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-babel#111]
Via https://github.com/rollup/rollup-plugin-json/pull/8#issuecomment-232450839

**Comment by Andarist** [comment]
@TrySound I'd like to fix this, but I'm thinking about adding `extensions` option rather than embedding it into default `include` - it seems to me that it's too easy to override `include` without being aware that it suddenly would allow other extensions. WDYT?

**Comment by TrySound** [comment]
I'm fine with it. Extensions is easier way.
