### ISSUE TITLE
Babili doesn't work as expected with rollup-plugin-babel

### ISSUE THREAD

**Issue by FezVrasta** [rollup/rollup-plugin-babel#112]
Hi, seems like babili doesn't work when used with your plugin.

https://github.com/babel/babili/issues/342

**Comment by Andarist** [comment]
I couldn't back track the issue to the commit with broken setup. I'm using rollup + rollup-plugin-babel + uglify for quite some time and I haven't noticed such issues - this leads me to think that it's not rollup-plugin-babel issue, but probably some other.

Inspecting both rollup-plugin-uglify and rollup-plugin-babel-minify source I see both use rollup's `transformBundle` hook so I assume they both should work the same (today ofc).

If the issue still persists I would love to take a look but would have to receive a repro case for this.
