### ISSUE TITLE
Failed to process <file>

### ISSUE THREAD

**Issue by FezVrasta** [rollup/rollup-plugin-babel#113]
I'm getting this error:

```
17 12 2016 09:30:26.552:ERROR [preprocessor.rollup]: Failed to process /Users/federicozivolo/Progetti/popper-js/tests/functional/tooltip.js

Error transforming /Users/federicozivolo/Progetti/popper-js/src/tooltip/node_modules/popper.js/build/popper.js with 'babel' plugin: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
```

I personally doubt it's this plugin's fault, but I'm reporting here because the message asks so 😇

More info about the problem and context:
https://github.com/rollup/rollup/issues/1155#issuecomment-267750186

**Comment by Andarist** [comment]
I see you have fixed ur issue (based on linked thread). I'm going to close this one then.
