### ISSUE TITLE
How to support IE8?

### ISSUE THREAD

**Issue by musicode** [rollup/rollup-plugin-babel#115]
The output code contans as below:

![image](https://cloud.githubusercontent.com/assets/2732303/21448639/f04d14a0-c91f-11e6-8c5d-e66329783d93.png)

is it compatible with IE8?

**Comment by RyanZim** [comment]
This relates to babel itself, relevant docs are here: https://babeljs.io/docs/usage/caveats/#internet-explorer

Please close this. Thanks!
