### ISSUE TITLE
babelrc ignore option confuses preflight check

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-babel#116]
Deleting `options.ignore` doesn't fix the problem of ignored files, because Babel picks it up when it resolves the `.babelrc` file

**Comment by Andarist** [comment]
This issue is quite old, not sure if it's still happening and I cannot assess that by looking at issue's title + posted description. 

Going to close it, but if there is something to be fixed please explain it in more detail to me and I'll try to fix it.
