### ISSUE TITLE
Sourcemap bug

### ISSUE THREAD

**Issue by oligot** [rollup/rollup-plugin-babel#121]
Hi,

I have a sourcemap bug (offset by one) when using rollup-plugin-babel.
I've created a [small repo](https://github.com/oligot/rollup-sourcemap) that shows how to reproduce the bug.

Basically, I put a breaking on a line that will print a message to the console (using console.log) and the message has already been printed to the console (meaning there is an offset by one bug).
The bug originally appeared in a bigger project but I tried to isolate it by reducing the project to its minimum.

Here is a screenshot showing the problem

![rollup](https://cloud.githubusercontent.com/assets/1004034/21687641/652194e6-d36a-11e6-810f-9371d5983ff9.png)

The bug disappears when I remove rollup-plugin-babel.

**Comment by oligot** [comment]
When using the Rollup API instead of the CLI, the bug disappears (see commit https://github.com/oligot/rollup-sourcemap/commit/3fca3b2b8b57ac86c2537ff2c048718aa1656806).

Using the API has the added benefit that one can more easily produce different targets (with or without babel) depending on the browser capabilities (does it implement ES2015 or not).
So, I'm going to stick to the Rollup API for now.

**Comment by shanewholloway** [comment]
I'm also seeing a similar off-by-one bug with sourcemaps (rollup@0.48.2, rollup-plugin-babel@3.0.2). I'll give the API a try; hopefully it'll solve my issue as well.

**Comment by egucciar** [comment]
Can't this be fixed? I would rather not change my build process for a silly sourcemap bug.

**Comment by egucciar** [comment]
@andarist unfortunately I do not have time to figure out what's going on here and fix it but considering that the issue isn't present when using the API maybe someone who developed this plugin should be able to easily update it to work.

**Comment by Andarist** [comment]
Based on the fact that this plugin doesnt do anything with generated sourcemaps other than just returning what it got from babel it seems to me that this is not this plugin's fault, but maybe babel's or rollup's. Anyhow the issue doesn't belong to this repository.

If there is still some issue around this I would expect it be a rollup's fault - maybe it doesn't change generated line numbers in a sourcemap after finalizing step (outputting a bundle in specified format - in example IIFE).
