### ISSUE TITLE
.babelrc files in src/

### ISSUE THREAD

**Issue by deckar01** [rollup/rollup-plugin-babel#122]
**Problem**

Placing a `.babelrc` file in the same directory as source files does not respect the nested configuration.

**References**

> Babel will look for a `.babelrc` in the current directory of the file being transpiled. If one does not exist, it will travel up the directory tree until it finds either a `.babelrc`, or a `package.json` with a `"babel": {}` hash within.

https://babeljs.io/docs/usage/babelrc/#lookup-behavior

> Before Babel will actually compile your code, it needs to be configured. Create a new file, `src/.babelrc`:
> 
>     {
>       "presets": ["es2015-rollup"]
>     }

http://rollupjs.org/guide/#using-rollup-with-babel

**Thoughts**

I suspect that the source files are being copied to a temporary location, before babel is invoked, without copying the `.babelrc` file(s).

---

The readme for this repo and the "Using Rollup with Babel" section of the rollup guide might need to be updated. They seem to reference old versions of the libraries first with notes and caveats for the latest versions. It would be nice if the documentation for the current version was the default, and support for older versions was secondary.

**Comment by Rich-Harris** [comment]
Can you provide a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)? It's using Babel's builtin lookup behaviour, so should work correctly (and it's worked correctly for me in the past).

> They seem to reference old versions of the libraries first with notes and caveats for the latest versions.

Can you show us where? Thanks

**Comment by deckar01** [comment]
After building a minimal repro I realized the issue was that `/src` had a `.babelrc` file, but `/lib` did not, so nothing in `/lib` was being transpiled, just rolled up. The issue seems to be caused by my lack of understanding of the order of operations. Sorry for the confusion.

---

I think my documentation gripe was rooted in thinking the "Configuring Babel" preamble implied the `es2015-rollup` preset was no longer supported. It sounds like I can go back to using `es2015-rollup` instead of manually configuring `.babelrc`.

Again, sorry for the confusion.
