### ISSUE TITLE
Can't find variable: regeneratorRuntime

### ISSUE THREAD

**Issue by Yaminonaka** [rollup/rollup-plugin-babel#129]
Hello.
I'm using Rollup for a project and everything went pretty well (thanks for this tool!) until I tried to use ES6 Generator. What ever I do in my configs file, the output never includes regeneratorRuntime. I spent the whole morning on this...
I'm using what is recommended in the readMe file (es2015-rollup preset in babel.rc, last version of rollup-plugin-babel, etc.).
Could anyone tell me if generator works in Browser and if yes, with what kind of configuration ?

Thanks in advance.

**Comment by Andarist** [comment]
Please read my answer [here](https://github.com/rollup/rollup-plugin-babel/issues/209#issuecomment-399260174)
