### ISSUE TITLE
Plugin does not work after upgrade

### ISSUE THREAD

**Issue by copperspeed** [rollup/rollup-plugin-babel#130]
I was use rollup-plugin-babel 1.0.0 then upgraded to 2.7.1 and it does not convert to es5 at all with no errors just leaves as ES6

File inside gulp task: 
`rollup.rollup({

          entry: "somefile",
          plugins: [
              nodeResolve({
                jsnext: true,
                module:true
              }),
            babel({
              exclude: "/node_modules/**",
            })
          ]
        })
        .then(bundle => {
          bundle.write({
            format: 'es',
            moduleName: 'gmst',
            sourceMap: true,
            dest: "/src/package/rollup.js"
          });
        });

.babelrc file

`{

  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "external-helpers"
  ]
}

If I switch back to version 1.0.0 it works. Thanks for your help.

**Comment by Andarist** [comment]
You'd have to share a full, runnable repro repository - without that we might not be able to help you. Knowing you had this issue quite long time ago I hope you have worked it out by now.
