### ISSUE TITLE
Incompatible with regenerator

### ISSUE THREAD

**Issue by ForbesLindesay** [rollup/rollup-plugin-babel#135]
I'm trying to use this with regenerator using the babel-plugin-transform-runtime to add the regeneratorRuntime helpers.  This is necessary otherwise you get a reference error.

```js
    babel({
      babelrc: false,
      presets: [
        ['env', {
          targets: {
            browsers: ['last 2 versions']
          },
          modules: false
        }],
        'stage-0',
        'react'
      ],
      plugins: [
        'transform-decorators-legacy',
        ['transform-runtime', {helpers: false, polyfill: false}],
        'external-helpers'
      ]
    })
```

I get the output:

```
Error: 'default' is not exported by node_modules/babel-runtime/regenerator/index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src/types/AnyType.js (1:7)
1: import _regeneratorRuntime from 'babel-runtime/regenerator';
          ^
2: import Type from './Type';
```

**Comment by josephfrazier** [comment]
I had a different problem with babel-plugin-transform-runtime, and happened across this issue while trying to solve it. Your babel configuration solved that problem for me (thanks for posting it!), but then I encountered the same problem as you. I was able to fix it by adding [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) to my `rollup.config.js`:

```js
import babel from "rollup-plugin-babel";
import nodeResolve from "rollup-plugin-node-resolve";
import commonjs from 'rollup-plugin-commonjs';

export default {
  entry: "src/index.js",
  dest: "lib/index.js",
  plugins: [
    nodeResolve(),
    commonjs({
      include: "node_modules/**"
    }),
    babel({ runtimeHelpers: true }),
  ],
  format: "cjs"
};
```

**Comment by Nufeen** [comment]
Can confirm it works correctly with `rollup-plugin-node-resolve` and `rollup-plugin-commonjs`.
This is how my rollup.config section looks in case of bundling for browsers:
```js
  {
    entry: 'index.js',
    format: 'es',
    dest: 'build/bundle.js',
    plugins: [
      resolve(),
      commonjs({
        include: "node_modules/**"
      }),
      babel({
        runtimeHelpers: true,
        exclude: 'node_modules/**'
      })
    ]
  },
```
Rather looks like a question of documentation than a real issue.

**Comment by Andarist** [comment]
Closing this as outdated and not actionable here - this plugin just runs babel over ur input files. It doesn't try to resolve dependencies or anything - if you find yourself having such issue it's an issue of ESM/CJS interoperability and should be raised in commonjs plugin repo.
