### ISSUE TITLE
dont support babel-preset-env

### ISSUE THREAD

**Issue by musicode** [rollup/rollup-plugin-babel#136]
I want to use `babel-preset-env` to run code in IE8, but I can't configure correctly.

Is it supported?

**Comment by prichodko** [comment]
Yes it is, see my answer to you here https://github.com/rollup/rollup-plugin-babel/issues/120#issuecomment-305948770

**Comment by prichodko** [comment]
Problem above didn't have to do anything with babel-preset-env. 
Can be closed.
