### ISSUE TITLE
 (babel plugin) It looks like your Babel configuration specifies a module transformer. 

### ISSUE THREAD

**Issue by xgz123** [rollup/rollup-plugin-babel#140]
~~~json
{
  "presets": [
    ["env", {
      "es2015": {
        "modules": false
      },
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"]
      }
    }],
    "react"
  ],
  "plugins": ["external-helpers"]
}
~~~

>🚨   (babel plugin) It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information

System:
~~~
macos elcaption
node v7.10.0
npm 5.0.0
"rollup-plugin-babel": "^2.7.1",
"babel-preset-env": "^1.5.1",
"babel-preset-react": "^6.24.1",
~~~

**Comment by camwiegert** [comment]
@xgz123 `modules` is a top-level key in `babel-preset-env`'s options.

```json
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"]
      }
    }],
    "react"
  ],
  "plugins": ["external-helpers"]
}
```

**Comment by xgz123** [comment]
@camwiegert thanks. Now I have this one:

> 🚨   (babel plugin) Options {"modules":false} passed to xxx/node_modules/babel-preset-react/lib/index.js which does not accept options. (While processing preset: "xxx/node_modules/babel-preset-react/lib/index.js")
src/index.js

It's very strange to get a totally different warning. So I think it's related to my rollup config. Those warning both disapeared after I remove `babelrc-rollup`
