### ISSUE TITLE
Exclude the module transformer ?

### ISSUE THREAD

**Issue by L3ARNING2B** [rollup/rollup-plugin-babel#143]
Hello and first thanks for your awesome work,

In order to exclude the module transformer does we have to set  `modules` to false in babel `presets` as `Configuring Babel` example
````
// .babelrc
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "external-helpers"
  ]
}
````

Or maybe the module transformer in this case is `external-helpers` cause it is a module dependency which apply transform on code by adding helpers ? 

If so, does it mean that babel preset `es2015-rollup` should be used better, which includes 'external helpers'? As in the example below:

````
// .babelrc
{
  "presets": [
    [
      "es2015-rollup",
    ]
  ]
}
````

**Comment by Andarist** [comment]
This is perfectly valid config. I use similar myself.
```json
// .babelrc
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "external-helpers"
  ]
}
```

Does it answer your question?
