### ISSUE TITLE
rollup-plugin-babel can not understand "..." in es6

### ISSUE THREAD

**Issue by Tao-Quixote** [rollup/rollup-plugin-babel#144]
I've put my .babelrc file in the src folder like this:

```
{
  "presets": [
    [
      "latest",
      {
        "es2015": {
          "modules": false
        }
      }
    ]
  ],
  "plugins": [
    "external-helpers"
  ]
}
```
And next, i put my rollup.config.js file in the root of the project like this:

```
import resolve from 'rollup-plugin-node-resolve'
import babel from 'rollup-plugin-babel'

export default {
  // entry: 'dist-loose/index.js',
  entry: 'src/index.js',
  format: 'es',
  plugins: [
      resolve(),
      babel({
        plugins: ['external-helpers'],
        externalHelpers: true,
        exclude: 'node_modules/**'
      })
    ],
  dest: 'dist/bundle.js',
  sourceMap: true
}
```
And next, i write a line of words in the package.json file's scripts like this:

```
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build-loose": "babel src --out-dir ./dist-loose --plugins=transform-runtime --presets=es2016,stage-2",
    "build": "babel src --out-file ./dist/ecg.js --plugins=transform-runtime --presets=es2015,stage-2",
    "compile": "rollup -c"
  }
```
finally, when i run ```npm run compile```, something went wrong and the error info is:

```
> ecg@0.0.1 compile /Users/taoxin/Downloads/ecg
> rollup -c

🚨   (babel plugin) /Users/taoxin/Downloads/ecg/src/index.js: Unexpected token (7:4)
undefined (7:4)


npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ecg@0.0.1 compile: `rollup -c`
npm ERR! Exit status 1
...
```
The content in the line 7  in the file```/Users/taoxin/Downloads/ecg/src/index.js``` is:
```
export default {
    $methods: {
        ...obj
    }
}
```
I've checked that the rollup-plugin-babel can transform "``" into es5, but why it can not understand "..." in es6, and how could i resolve this problem?

I've read the document of the rollup-plugin-babel, but there is no more information about how to sovle this problem and there is no more settings for rollup-plugin-babel in rollup.config.js file.

Sorry for my English.

**Comment by zaygraveyard** [comment]
The [Object Rest/Spread Properties proposal](https://github.com/tc39/proposal-object-rest-spread) is still in [stage 3](https://github.com/tc39/proposal-object-rest-spread#status-of-this-proposal) which means its not yet part of the ECMAScript standard. So to use it you need to either add babel's [`stage-3` preset](https://babeljs.io/docs/plugins/preset-stage-3/) or babel's [`transform-object-rest-spread` plugin](https://babeljs.io/docs/plugins/transform-object-rest-spread/) to your `.babelrc`.

And BTW, babel's [`latest` preset has been deprecated and replaced by `env`](https://babeljs.io/docs/plugins/preset-latest/).

**Comment by Andarist** [comment]
What @zaygraveyard said 😉
