### ISSUE TITLE
rollup won't exclude babel-runtime if it's within `node_modules`

### ISSUE THREAD

**Issue by danielberndt** [rollup/rollup-plugin-babel#148]
Here's my config:

```js
export default {
  entry: "src/index.js",
  plugins: [
    resolve(),
    commonjs({include: "node_modules/**"}),
    babel({
      exclude: "node_modules/**", // only transpile our source code,
      runtimeHelpers: true,
      presets: [],
      plugins: [
        "transform-class-properties",
        ["transform-object-rest-spread", {useBuiltIns: true}],
        [
          "transform-runtime",
          {
            polyfill: false,
            regenerator: false,
          },
        ],
      ],
    }),
  ],
  external: [],
};
```

and I'm using these versions:

```
    "rollup": "^0.43.0",
    "rollup-plugin-babel": "^2.7.1",
    "rollup-plugin-commonjs": "^8.0.2",
    "rollup-plugin-node-resolve": "^3.0.0"
```

which will result in including this in my final bundle: (when using object-rest-spreads)
```js
var objectWithoutProperties = createCommonjsModule(function (module, exports) {
"use strict";

exports.__esModule = true;

exports.default = function (obj, keys) {...};
});
```

The only workaround I could find so far has been hiding the existence of the `babel-runtime` within my node-modules:

```js
  plugins: [
    resolve({
      customResolveOptions: {
        isFile: function(file, cb) {
          if (file.indexOf("babel-runtime") > 0) return cb(null, false);
          fs.stat(file, function(err, stat) {
            if (err && err.code === "ENOENT") cb(null, false);
            else if (err) cb(err);
            else cb(null, stat.isFile());
          });
        },
      },
    }),
    commonjs({include: "node_modules/**"}),
  //...
```

Now it's resulting in what I'm expecting it to do:

```js
import _objectWithoutProperties from 'babel-runtime/helpers/objectWithoutProperties';
```

Is this a bug or am I maybe just missing something?

**Comment by danielberndt** [comment]
Okay, I've found a much more elegant workaround:
```js
export default {
  // ...
  external: (id) => id.indexOf("babel-runtime") === 0,
}
```

But maybe this whole issue is based on a misunderstanding, of how `babel-runtime` is supposed to be used. My thinking is to avoid as much duplication in my libraries as possible. So externalising all calls to only one `babel-runtime` seems like a good idea, since I don't trust code de-duplication enough to be able detect all internalised babel-runtime part when bundling the final app.

**Comment by abesamiskevin** [comment]
Ran into the same problem today. Thankfully, the solution @danielberndt provided worked.

That said, I was also under the impression that telling babel to exclude "node_modules/**" should have excluded everything under the node_modules folder, including babel-runtime.

**Comment by Andarist** [comment]
`exclude` tells this plugin not to run babel transform over some files (in this example it shouldnt run it over files in `node_modules`). 

This is something entirely different from the issue presented here - by using `transform-runtime` you are putting imports/requires to `babel-runtime` modules into your source files (not into your node_modules). By doing so rollup includes them in the dependency graph, just like normal.

Imagine this situation:
```js
// src/index.js
import add from 'add'
console.log(add(2, 2))
```

Without specifying `external` rollup will include `add` module into your bundle as it tries to bundle everything together (its primary goal is being a bundler after all).

The fact that `babel-runtime` references are inserted "dynamically" into your source code through `transform-runtime` doesn't change anything when it comes to external bundling - to stop it you have to use `external` option appropriately.

When building libraries I usually do this:
```js
import pkg from "./package.json";

const external = [
  ...Object.keys(pkg.peerDependencies || {}),
  ...Object.keys(pkg.dependencies || {}),
];

const makeExternalPredicate = externalArr => {
  if (externalArr.length === 0) {
    return () => false;
  }
  const pattern = new RegExp(`^(${externalArr.join("|")})($|/)`);
  return id => pattern.test(id);
}

export default {
  input: 'src/index.js',
  output: {},
  external: makeExternalPredicate(external),
}
```
