### ISSUE TITLE
preset es2015 and es2015-rollup

### ISSUE THREAD

**Issue by henriklundgren** [rollup/rollup-plugin-babel#15]
My rollup build process needs `es2015-rollup`, but my mocha test needs `es2015`. I need a workflow that gets me to use both. Any help appreciated.

**Comment by Rich-Harris** [comment]
You could try putting the `.babelrc` needed by Mocha in your `tests` folder, and passing configuration directly to rollup-plugin-babel:

```js
plugins: [
  babel({ presets: [ 'es2015-rollup' ] })
]
```

**Comment by henriklundgren** [comment]
Yes,
Thank you
