### ISSUE TITLE
rollup-plugin-babel can not understand jsx syntax

### ISSUE THREAD

**Issue by Firanolfind** [rollup/rollup-plugin-babel#152]
I tried to use `rollup` in my react project. I tried this [guide ](https://oroboro.com/rollup-babel-react/)but `rollup -c` fails with this error(below). It seems that babel cant understand **react _jsx_** syntax, but react mentioned in babelrc.
What I am doing wrong, is it `rollup-plugin-babel` issue?

```bash
> rollup -c
🚨   (babel plugin) SyntaxError: C:/Users/farid.niftiyev/Work/Kristall/dev/source/client/index.js: Unexpected token (20:1)
source\client\index.js (20:1)
```

`index.js`
```javascript
//...
ReactDOM.render(
	<App/>,
	document.getElementById('root')
);
```
 `.babelrc`
```json 
{
  "presets": [ "es2015-rollup", "react" ],
  "plugins": [ "external-helpers", "transform-decorators-legacy" ]
}
```

`rollup.config.js`
```javascript
const 
	Babel		= require('rollup-plugin-babel'),
	Rollup		= require('rollup-stream'),
	RollupBabel	= require('rollup-plugin-babel'),
	Resolve		= require('rollup-plugin-node-resolve'),
	CommonJs	= require('rollup-plugin-commonjs'),
	Replace		= require('rollup-plugin-replace');

module.exports = {
	entry:		'source/client/index.js',
	dest: 		'build/bundle.js',
	format:		'iife',
	plugins: [
		Babel({
			 // exclude: 'node_modules/**'
			 exclude: [
				'node_modules/**',
				'**/*.json'
			],
		}),
		Resolve({
			jsnext: true
		}),
		CommonJs({
			include: 'node_modules/**',
			namedExports:
			{
				'./node_modules/react/react.js': 
				['cloneElement', 'createElement', 'PropTypes', 'Children', 'Component'],
			}
		}),
		Replace({
		 'process.env.NODE_ENV': JSON.stringify( 'production' )
		}),
	],
	sourceMap: false, // true | inline
};
```

**Comment by iabw** [comment]
I'm encountering this error when I have a commented out require call.

I'm not clear if require calls mixed with import/export should even work, but this seems extra weird, since I would expect comments to be (more or less) ignored.

Rolled up correctly:
```
import React, { Component } from 'react';

export class Wrapper extends Component {

  render() {
    return (
      <div />
    );
  }
}
```

Unexpected token (8:6):
```
import React, { Component } from 'react';
// var foo = require('bar');

export class Wrapper extends Component {

  render() {
    return (
      <div />
    );
  }
}
```

This class is exported out of my index.js, like:
```
export { Wrapper } from './Wrapper';
```

My rollup.config.js looks like
```
import babel from 'rollup-plugin-babel'
import commonjs from 'rollup-plugin-commonjs'
import postcss from 'rollup-plugin-postcss'
import resolve from 'rollup-plugin-node-resolve'

import pkg from './package.json'

export default {
  input: 'src/index.js',
  output: [
    {
      file: pkg.main,
      format: 'cjs'
    },
    {
      file: pkg.module,
      format: 'es'
    }
  ],
  external: [
    'react',
    'react-dom',
    'prop-types'
  ],
  plugins: [
    resolve(),
    commonjs(),
    postcss({
    }),
    babel({
      exclude: 'node_modules/**'
    })
  ]
}
```

and .babelrc like:
```
{
  "presets": [
    ["env", {
      "modules": false
    }],
    "stage-0",
    "react"
  ],
  "plugins": [
    "external-helpers"
  ]
}
```

which I believe are both unchanged from this boilerplate I started with - https://github.com/transitive-bullshit/react-modern-library-boilerplate

I could provide a repro repo if needed, but there's nothing more to it than the above boilerplate.

**Comment by iabw** [comment]
I'm not familiar enough with transpiling to sort out what [rollup-plugin-commonjs is doing in transform.js](https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/transform.js#L90), but the behavior mentioned in [this comment](https://github.com/rollup/rollup/issues/1058#issuecomment-254187433) seems suspicious in this context.

**Comment by MrJadaml** [comment]
Had a similar issue and installed the react preset:

`npm install --save-dev babel-preset-react`

 Adding react to my _.babelrc_ presets and got a clean build

` "presets": ["es2015-rollup", "react"]`

**Comment by Andarist** [comment]
JSX is non-standard language extension, so naturally it is not supported by all the tools (in this case by rollup).  As suggested - you need to configure babel correctly, which means adding a react preset or jsx transform directly.

**Comment by arizonatribe** [comment]
He _did_ configure it correctly (as it shows in his code output)

**Comment by DominicTobias** [comment]
For me I had to add an exclude for `rollup-plugin-commonjs`:

```
commonjs({
    exclude: 'src/**',
}),
```
