### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by Riim** [rollup/rollup-plugin-babel#155]
Sorry for my English.

When upgrading from version 3.0.0 to version 3.0.1 the error occurs:
```
(babel plugin) TypeError: /Users/Riim/dev/cellx/src/x.js: Property declaration of ExportDefaultDeclaration expected node to be of a type ["FunctionDeclaration","ClassDeclaration","Expression"] but instead got "ExpressionStatement"
src/cellx.js
```
File `/Users/Riim/dev/cellx/src/x.js` in system not exist.
If I comment all content of the input file (https://github.com/Riim/cellx/blob/master/src/cellx.js), an error is still present.

Thanks!

**Comment by petamoriken** [comment]
@hzoo I got the same error in v3.0.1 (maybe this occurred by #154):

> Error: (babel plugin) TypeError: /home/travis/build/petamoriken/float16/src/x.js: Property declaration of ExportDefaultDeclaration expected node to be of a type ["FunctionDeclaration","ClassDeclaration","Expression"] but instead got "ExpressionStatement"
src/index.js

https://travis-ci.org/petamoriken/float16/builds/262640105

related: #156

**Comment by michalbe** [comment]
Downgrading to `"rollup-plugin-babel": "^2.7.1"` seems to solve this issue.
