### ISSUE TITLE
transform-decorators throws error in babel 7

### ISSUE THREAD

**Issue by zerkalica** [rollup/rollup-plugin-babel#160]
Error appears only in

1. babel 7
2. if transform-decorators (not legacy) plugin added
3. If rollup-plugin-babel version >= 3.0.1, 3.0.0-alpha.17 works fine

.babelrc:
```json
{
  "presets": [
    "flow",
    "react",
    "stage-0",
    ["es2015", {"loose": true}]
  ],
  "plugins": [
    "transform-decorators",
    ["transform-class-properties", {"loose": true}],
    ["transform-react-jsx", {"pragma": "lom_h"}]
  ]
}
```

package.json:

```json
{
  "devDependencies": {
       "babel-plugin-external-helpers": "^7.0.0-alpha.19",
       "babel-plugin-transform-class-properties": "^7.0.0-alpha.19",
       "babel-plugin-transform-decorators": "^7.0.0-alpha.19",
       "babel-preset-es2015": "^7.0.0-alpha.19",
       "babel-preset-flow": "^7.0.0-alpha.19",
       "babel-preset-react": "^7.0.0-alpha.19",
       "babel-preset-stage-0": "^7.0.0-alpha.19",
       "rollup": "^0.48.2",
       "rollup-plugin-babel": "^3.0.2"
  }
}
```

Error:

```
[!] (babel plugin) Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
src/examples/t.js
Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
    at error (/home/yuferev/projects/rdi-examples/node_modules/rollup/dist/rollup.js:181:12)
    at Object.error$1 [as error] (/home/yuferev/projects/rdi-examples/node_modules/rollup/dist/rollup.js:9411:6)
    at /home/yuferev/projects/rdi-examples/node_modules/rollup/dist/rollup.js:9420:32
    at <anonymous>
```

**Comment by luzat** [comment]
I am getting the same error with either `@babel/plugin-proposal-decorators` or `@babel/plugin-external-helpers` (not sure if related) 7.0.0-beta.35 enabled. Both seem to work fine with babel-cli (without rollup).

It seems that a lot of errors cause this output. Is it possible to get better error messages which may actually point at the root cause?

**Comment by Andarist** [comment]
If you are using babel@7 then please upgrade to the newest versions which are scoped now, so you'd have to remove your old babel dependencies and add new ones, ie. `@babel/preset-react`.

Also babel@7 is supposed to work with `rollup-plugin-babel@4.0.0-beta.0`, please upgrade it too.

**Comment by tswaters** [comment]
Can this be added to the readme?   Currently there is no indication that there is a `4.0.0-beta.0` version available from `npm i rollup-plugin-babel@next`.... it's in CHANGELOG, but it might be good to add to readme.

**Comment by Andarist** [comment]
We would happily accept a PR with such a note added to the README

**Comment by FinesseRus** [comment]
I can't get the combination of Rollup, Babel, and the transform-decorators plugin to work. I always get error `An unexpected situation arose.`. I tried both stable and beta versions of Rollup and Babel.

Has anyone succeed to make this combination work? Could you please share you setup?
