### ISSUE TITLE
Update to use env instead of es2015

### ISSUE THREAD

**Issue by rbiggs** [rollup/rollup-plugin-babel#169]
When using this plugin, I'm getting the following warning from Babel:

`
npm WARN deprecated babel-preset-es2015@6.24.1: We're super 😸  excited that you're trying to use ES2015 syntax, but instead of continuing yearly presets 😭 , we recommend using babel-preset-env: npm install babel-preset-env. preset-env without options will compile ES2015+ down to ES5. And by targeting specific browsers, Babel can do less work and you can ship native ES2015+ to users 😎 ! Also, we are in the process of releasing v7, so give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and test it! Thanks so much for using Babel 🙏 , please give us a follow @babeljs for updates, join slack.babeljs.io for discussion and help support at opencollective.com/babel
`

**Comment by jsg2021** [comment]
that’s probaly from your babel config. not from this plugin.

**Comment by rbiggs** [comment]
Narrowed it down to `babel-preset-es2015-rollup`. Logged issue with them.
