### ISSUE TITLE
Use babel-runtime instead of external-helpers [feature/question]

### ISSUE THREAD

**Issue by chpio** [rollup/rollup-plugin-babel#17]
hi,

when i use this plugin (*babel-plugin-transform-runtime* enabled) i get a file with external helpers ***and*** runtime imports. Is there an option to disable this behavior (only use runtime) as i don't need the doubled amount of helpers in my code... :)

**Comment by Rich-Harris** [comment]
This works as of 2.3.0 – just add the `runtimeHelpers: true` option when you initialise rollup-plugin-babel, and it will use runtime helpers instead of putting them at the top of the bundle.

**Comment by chpio** [comment]
wow, thank you :+1:
