### ISSUE TITLE
`rollupPluginBabelHelpers` is imported also when not necessary in 4.0.0-beta.0

### ISSUE THREAD

**Issue by edoardocavazza** [rollup/rollup-plugin-babel#176]
The `babelHelpers` auto import with version 4.0.0-beta.0 brokes the interoperability with `rollup-plugin-commonjs` and JSX:

## Sample
Bundling files with JSX, commonjs and babel.

**Config 1:**
```js
plugins: [
   ...,
  common(),
  babel(),
]
```
It fails because `common` does not handle JSX.

**Config 2:**
```js
plugins: [
   ...,
  babel(),
  common(),
]
```
`common` skips the file because `rollupPluginBabelHelpers` is imported (also when not needed), so it fails.

**Config 3:**
```js
plugins: [
   ...,
  babel({ plugins: [ ['@babel/plugin-transform-react-jsx', { pragma: 'h' }] ] }),
  common(),
  babel(other config),
]
```
It failes because `rollupPluginBabelHelpers` is imported more than once.

**Comment by Andarist** [comment]
**Config 1**
See [this](https://github.com/rollup/rollup-plugin-commonjs/issues/244)

You probably have updates `rollup-plugin-commonjs` as well, you should reorder ur plugins - `babel` should come before passing its output to the `commonjs` plugin.

**Config 2**
Ain't exactly sure about it, but sounds it might be the same problem as with **Config 1**. Inserting `rollupPluginBabelHelpers` event when not needed shouldn't cause any problems, it should just get tree-shaken away.

**Config 3**
Sounds like a weird config. Why are you transpiling with babel twice?

**Comment by edoardocavazza** [comment]
Hi @Andarist 

I have never used twice babel configurations, **Config 3** was just a try to precompile JSX before the commonjs plugin.

I think the most important case is **Config 2**, but it does not seem to work. I don't know if treeshaking (that could be dangerously disabled) is executed before the next plugin call, so before the commonjs check. As you can see [here](https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/transform.js#L56), if commonjs detects a `import` (in this case `import rollupPluginBabelHelpers`) statement, it flags the source as ES module.

**Comment by Andarist** [comment]
Could u setup a simple repository illustrating the issue? Would help a lot with fixing this fast.

Are you writing your code commonjs style so inserting an import statement causes problems for u?

**Comment by Andarist** [comment]
Probably we could move inserting `rollupPluginBabelHelpers` logic into the [`helperPlugin`](https://github.com/rollup/rollup-plugin-babel/blob/529a011cec8caf80582d23d59949c5e0236de1d9/src/helperPlugin.js) and use `@babel/helper-module-imports` in there.

**Comment by edoardocavazza** [comment]
I have a bunch of third party umd dependencies that needs to be transpiled, so I have to use both babel and common plugins on that files. It's not a common scenario, but in very large application it could happen. I am preparing a sample repository ;)

**Comment by Andarist** [comment]
Ok, I guess I understand what's happening, just wondering if my proposed solution (using `@babel/helper-module-imports`) will be enough or something else needs to be done.

Your sample repository will help a lot with moving fast on this! Thanks for preparing it.

**Comment by edoardocavazza** [comment]
Sample repository: [https://gitlab.com/edoardo.cavazza/rollup-plugin-babel-issue-176](https://gitlab.com/edoardo.cavazza/rollup-plugin-babel-issue-176)

**Comment by Andarist** [comment]
Thanks! Will try to work on fixing this today/tomorrow

**Comment by Andarist** [comment]
I got to play with this a little, can't figure it out yet how to do it properly. I have a strong feeling though that this thing here is hacky anyway and just a proper way of doing this should be exposed by babel itself, so in example webpack's babel-loader could benefit from it. Gonna file an issue in babel's repo so we can discuss further about proposed solution, just need to gather info what APIs are at the moment exposed for inserting helpers in various forms.

**Comment by edoardocavazza** [comment]
It's working now 🎉🎉🎉

Just a note, I have this rollup warning:
```
commonjs-proxy:rollupPluginBabelHelpers (1:140) 'default' is not exported by 'rollupPluginBabelHelpers
```

**Comment by Andarist** [comment]
Yeah, I know about it but its coming from the commonjs plugin. I think when transpiling your commonjs file babel inserts transpiled version of the import statements for `rollupPluginBabelHelpers`, and the commonjs must consider that it might be a commonjs module or that ur file might want to mutate what got required and it wraps requested module with a commonjs proxy which tries to do this:
```js
// commonjs-proxy:rollupPluginBabelHelpers
export default ( rollupPluginBabelHelpers && rollupPluginBabelHelpers['default'] ) || rollupPluginBabelHelpers
```
which in turn trigger some mechanism in rollup checking that `default` is not exported by `rollupPluginBabelHelpers`. 

Anyway I consider this a minor issue and personally I don't intend to provide a fix for it right now, mainly because I'm lacking time to dig into this any further.

**Comment by flyyang** [comment]
Any update on this?
