### ISSUE TITLE
debug option to babel isn't respected in n+1 rollup outputs

### ISSUE THREAD

**Issue by jasonkarns** [rollup/rollup-plugin-babel#179]
I'm using rollup to build 3 output files. The configuration is set via `rollup.config.js`, exporting an array of three configurations (one per output).

The debug option is set to true for all three outputs, but only the first is respected.

<details>
<summary>rollup.config.js</summary>
<pre><code>
[
  { // module
    input: 'src/index.js',
    external: [ 'lodash.merge' ],
    plugins: [
      babel({
        babelrc: false,
        exclude: 'node_modules',
        presets: [
          [ 'env', {
            debug: true,
            modules: false,
            targets: { node: 8 }
          }]]})],
    output: {
      file: module,
      format: 'cjs',
      sourcemap: true }
  },
  { // main
    input: 'src/index.js',
    external: [ 'lodash.merge' ],
    plugins: [
      babel({
        babelrc: false,
        exclude: 'node_modules',
        presets: [
          [ 'env', {
            debug: true,
            modules: false,
            targets: {
              node: 6
            }}]]})],
    output: {
      file: main,
      format: 'cjs',
      sourcemap: true }
  },
  { // browser
    plugins: [
      input: 'src/index.js',
      commonjs(),
      resolve(),
      babel({
        babelrc: false,
        exclude: 'node_modules',
        presets: [
          [ 'env', {
            debug: true,
            modules: false,
            targets: {
              browsers: browserslist
            }}]]})],
    output: {
      file: 'dist/index.js',
      format: 'umd',
      name: 'LittleSister',
      sourcemap: true }
  }
]
</code></pre>
</details>

When run, (`rollup -c`), the output only prints the babel "debug" output for the first bundle:

<details>
<summary>rollup -c</summary>
<pre><code>
src/index.js → ./lib/index.js...
babel-preset-env: `DEBUG` option

Using targets:
{
  "node": "8"
}

Modules transform: false

Using plugins:
created ./lib/index.js in 149ms

src/index.js → ./index.js...
created ./index.js in 85ms

src/index.js → dist/index.js...
</code></pre>
</summary>

**Comment by loganfsmyth** [comment]
This isn't really a rollup issue, it's part of `babel-preset-env`. It only logs the first set of options which if I had to guess is due to limitations in the implementation for Babel 6.x. I'd recommend re-filing in https://github.com/babel/babel, and we can probably have a conversation about this being changed for Babel 7.x since the previous limitation no longer really applies.

**Comment by jasonkarns** [comment]
"re-log"... there's an existing issue for it? (I can't find any existing issue to reference or re-open...) Is babel caching something between runs or something? I can't quite understand how this could be a babel bug, considering each of these should be completely independent invocations of babel. (Unless either rollup or babel is caching something somehow?)

**Comment by loganfsmyth** [comment]
> there's an existing issue for it?

No, I don't think there is.

By default in Babel 6, presets are executed for every single file that is compiled. That means a naive implementation of `babel-preset-env` would absolutely fill your console with debug output whenever you compiled any reasonably-sized project. To avoid spamming the user's console, the preset just has a global [`hasBeenLogged`](https://github.com/babel/babel/blob/cf62908bbd21a844e868ee76afd718faed699c88/packages/babel-preset-env/src/index.js#L93) flag.

In Babel 7, we make a best effort to only execute presets however many times they are declared in the user's config, so we can probably drop that flag and rely on babel-core to not call the preset over and over.

**Comment by jasonkarns** [comment]
Ah!, thanks for clarifying. I was digging through babel issues and only found this one that seemed even the slightest bit related... https://github.com/babel/babel/issues/6634

But I guess it's not. Thanks for illuminating...

**Comment by jasonkarns** [comment]
I'm gonna try some hack workaround to force unload babel in between builds in rollup...

**Comment by jasonkarns** [comment]
closing here as the issue is apparently in babel proper (or present-env, rather)

Intent to fix documented in https://github.com/babel/babel/issues/6634
