### ISSUE TITLE
Jest, Babel and Rollup require conflicting modules setting?

### ISSUE THREAD

**Issue by njlr** [rollup/rollup-plugin-babel#185]
To run `rollup -c`, I need this in my `.babelrc`: 

    [
      "@babel/preset-env", {
        "targets": {
          "node": "6.10"
        }, 
        "modules": false
      }
    ]

Otherwise I get: 

> [!] (babel plugin) Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information

However, this prevents Jest from working: 

> SyntaxError: Unexpected token import

What is the recommended approach here?

**Comment by nicolo-ribaudo** [comment]
You can use different envs:
```json
{
  "env": {
    "test": {
      "presets": [
        ["@babel/preset-env", { "modules": "cjs" }]
      ]
    },
    "build": {
       "presets": [
          ["@babel/preset-env", { "modules": false }]
        ]
     }
  }
}
```

```
$ BABEL_ENV=build rollup -c

$ BABEL_ENV=test jest
```

**Comment by njlr** [comment]
I wasn't aware of that feature. Cheers!

**Comment by loganfsmyth** [comment]
Is `"cjs"` right? I think it would be `"commonjs"`, or just leave it out as `["@babel/preset-env", {}]` or `"@babel/preset-env"` would work.
