### ISSUE TITLE
babelHelpers is not defined

### ISSUE THREAD

**Issue by Eugeno** [rollup/rollup-plugin-babel#186]
Code in Gulp looks like:
```
babel({
  babelrc: false,
  exclude: 'node_modules/**',
  presets: [
    ['env', {
      'modules': false
    }]
  ],
  plugins: [
    'external-helpers'
  ]
})
```

Some dependencies:
```
"babel-plugin-external-helpers": "^6.22.0",
"babel-preset-env": "^1.6.1",
"rollup-plugin-babel": "3.0.2",
```

I've tried a lot of things from search, but there is no success: console always tells me `Uncaught ReferenceError: babelHelpers is not defined`

**Comment by Eugeno** [comment]
Made [test repository](https://github.com/Eugeno/rollup-babel-test)

**Comment by LucaMele** [comment]
Same issue here

**Comment by LucaMele** [comment]
I found a work around. Fix version on 3.0.2 in your package json, remove node modules and package-lock.json.

The issue came from this version: https://github.com/rollup/rollup-plugin-babel/compare/v3.0.3...master

**Comment by LucaMele** [comment]
I could fix the issue by fixing rollup version on :

"rollup": "0.50.0"

**Comment by LucaMele** [comment]
I just tried the newst rollup version and that works as well..

**Comment by Eugeno** [comment]
@LucaMele it's weird, [but it works](https://github.com/Eugeno/rollup-babel-test/commit/1e179048e16cf8a733dd8ed9f4037ff1b7d10101).
Not with the newest version, but anyway =)

**Comment by mo** [comment]
I hit this too today using:
   "rollup": "^0.55.3",
    "rollup-plugin-babel": "^3.0.3",

Pinning to:
   "rollup": "0.50.",
    "rollup-plugin-babel": "3.0.3",

...did _not_ fix it for me.

**Comment by LucaMele** [comment]
try 0.50.1

**Comment by mo** [comment]
0.50.1 has the same for bug for me as well

**Comment by LucaMele** [comment]
weird for me that version fixed the issue. Did you try to do: `npm cache clean --force && rm -R node_modules && npm i` before?

**Comment by mo** [comment]
When I run rollup 0.50.0, 0.50.1 and latest there is no difference in the generated output.

However, I found this:
https://github.com/storybooks/storybook/issues/1320#issuecomment-310777396

...and that fix works for me.

**Comment by Andarist** [comment]
The issue seems to be resolved with advice linked by @mo . With new rollup-plugin-babel (currently in beta because it's going to target babel@7) you won't have to include `external-helpers` plugin at all.
