### ISSUE TITLE
rollupPluginBabelHelpers is always included

### ISSUE THREAD

**Issue by feross** [rollup/rollup-plugin-babel#187]
Using `rollup-plugin-babel@^4.0.0-beta.1`, a full list of babel helpers is included, even though most of them are not needed.

I found this in the output:

```js
var rollupPluginBabelHelpers = Object.freeze({
	get typeof () { return _typeof; },
	jsx: _jsx,
	asyncIterator: _asyncIterator,
	AwaitValue: _AwaitValue,
	AsyncGenerator: _AsyncGenerator,
	wrapAsyncGenerator: _wrapAsyncGenerator,
	awaitAsyncGenerator: _awaitAsyncGenerator,
	asyncGeneratorDelegate: _asyncGeneratorDelegate,
	asyncToGenerator: _asyncToGenerator,
	classCallCheck: _classCallCheck,
	createClass: _createClass,
	defineEnumerableProperties: _defineEnumerableProperties,
	defaults: _defaults,
	defineProperty: _defineProperty,
	get extends () { return _extends; },
	get: _get,
	inherits: _inherits,
	inheritsLoose: _inheritsLoose,
	wrapNativeSuper: _wrapNativeSuper,
	instanceof: _instanceof,
	interopRequireDefault: _interopRequireDefault,
	interopRequireWildcard: _interopRequireWildcard,
	newArrowCheck: _newArrowCheck,
	objectDestructuringEmpty: _objectDestructuringEmpty,
	objectWithoutProperties: _objectWithoutProperties,
	assertThisInitialized: _assertThisInitialized,
	possibleConstructorReturn: _possibleConstructorReturn,
	set: _set,
	slicedToArray: _slicedToArray,
	slicedToArrayLoose: _slicedToArrayLoose,
	taggedTemplateLiteral: _taggedTemplateLiteral,
	taggedTemplateLiteralLoose: _taggedTemplateLiteralLoose,
	temporalRef: _temporalRef,
	readOnlyError: _readOnlyError,
	classNameTDZError: _classNameTDZError,
	temporalUndefined: _temporalUndefined,
	toArray: _toArray,
	toConsumableArray: _toConsumableArray,
	skipFirstGeneratorNext: _skipFirstGeneratorNext,
	toPropertyKey: _toPropertyKey,
	initializerWarningHelper: _initializerWarningHelper,
	initializerDefineProperty: _initializerDefineProperty,
	applyDecoratedDescriptor: _applyDecoratedDescriptor
});
```

The only helper that is actually used by my code is `objectWithoutProperties`, so this is hugely excessive.

Relevant part of the `rollup.config.js`:

```js
  plugins: [
    nodeResolve({
      // Use the `package.json` "browser" field
      browser: true,
      // Resolve .mjs and .js files
      extensions: ['.mjs', '.js'],
      // Prefer node.js built-ins instead of npm packages
      preferBuiltins: true
    }),
    nodeBuiltins(),
    babel({
      exclude: 'node_modules/**'
    }),
    commonjs()
  ]
```

I was under the assumption that  does `rollup-plugin-babel` could automatically deduplicate babel-helpers, based on the warning in this line: https://github.com/rollup/rollup-plugin-babel/commit/7796ce963322bab5877ca90f06c30aec65bf71b6#diff-1fdf421c05c1140f6d71444ea2b27638R59

I tried passing the `externalHelpers: true` option, no luck. Then I tried the `runtimeHelpers: true` option (with the transform-runtime babel plugin). Nothing prevents the babel helper functions from being included!

**How can I include only the babel helpers which are actually used?**

**Comment by pascalduez** [comment]
This is how I ended up preventing the runtime helpers from being included in the bundle, by using the `external` key:  
https://github.com/pascalduez/react-module-boilerplate/pull/6/files#diff-ff6e5f22a9c7e66987b19c0199636480R10

Not sure what the `externalHelpers: true` or `runtimeHelpers: true` options are useful for then...

**Comment by Andarist** [comment]
You can pass `externalHelpersWhitelist` to control this on your own.

However I *suspect* that you somehow use those helpers in some CJS file and that caused them to be converted to CJS and thus prevented tree-shaking. I'm not 100% sure about this - would need to see a repro case, can you provide one?

**Comment by feross** [comment]
@Andarist Can I confirm, to make sure I understand correctly? So, if there's any CJS file that uses a Babel feature like object rest/spread, then treeshaking won't work and the entire list of helpers will end up in the output bundle. Correct?

**Comment by Andarist** [comment]
Yeah, that's the case for now. Question is - why there is a CJS file bundled? Is it coming from node_modules? Or is your codebase a mix of ESM & CJS?

**Comment by feross** [comment]
My codebase is currently a mix of ESM & CJS. Migrating it over to ESM progressively.

**Comment by Andarist** [comment]
Ok, going to close this issue then. Feel free to comment further though.
