### ISSUE TITLE
"Unexpected situation arose" error with transform-decorators-legacy plugin

### ISSUE THREAD

**Issue by arackaf** [rollup/rollup-plugin-babel#188]
Repo: https://github.com/arackaf/booklist/tree/feature/rollup  (the rollup branch specifically).

In the `react-redux` folder, `npm i`, then do `npm run rollup`.  You should get an error of

> An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!

Removing the `"transform-decorators-legacy"` babel plugin causes the error to go away (and nothing else seems to).

**Comment by FinesseRus** [comment]
can't get the combination of Rollup, Babel, and the `transform-decorators-legacy` plugin to work. I tried both stable and beta versions of Rollup and Babel. I always get error `An unexpected situation arose`.

Has anyone succeed to make this combination work? Could you please share you setup?

**Comment by mnpenner** [comment]
I'm getting this too with `transform-decorators-legacy`. Removing it fixes the error. Not sure about a solution; I actually don't need the transform.

**Comment by Andarist** [comment]
There was a fix released some time ago, please try new rollup-plugin-babel and if the problem persists please report it back as a new issue.
