### ISSUE TITLE
Babel 7's `ignore` or `only` cause the plugin to throw

### ISSUE THREAD

**Issue by loganfsmyth** [rollup/rollup-plugin-babel#192]
Should be a quick fix. Babel 7's `babel.transform` returns `null` if the file it was given has been ignored, which causes an exception since this plugin tries to read `result.code`.

Source:
https://stackoverflow.com/questions/48811861/gulp-rollup-babel-fail-on-build

**Comment by Andarist** [comment]
Preparing a fix for this.
