### ISSUE TITLE
Restore NUL convention for helper name

### ISSUE THREAD

**Issue by NMinhNguyen** [rollup/rollup-plugin-babel#197]
Hey,

I've noticed a regression when this plugin is used with [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve), and I think it's related to the fact that https://github.com/rollup/rollup-plugin-babel/commit/d169da1f6cea0792fedd386678049b092bbfc9f3 was undone by #170:

https://github.com/Andarist/rollup-plugin-babel/blob/25d02c0c8de4ff67c60140e85d67cfc85801ffc2/src/constants.js#L5

If you take a look at https://github.com/rollup/rollup-plugin-node-resolve/blob/313a3e32f432f9eb18cc4c231cc7aac6df317a51/src/index.js#L74 you can see that there appears to be a convention whereby

> IDs with null character, these belong to other plugins

I'll try to produce a repro later today, but making the following change locally in my `node_modules` helps me get around the issue:

```diff
-export const HELPERS = 'rollupPluginBabelHelpers';
+export const HELPERS = '\0rollupPluginBabelHelpers';
```

cc @Andarist who seemed to say there's an [issue](https://github.com/rollup/rollup-plugin-babel/pull/170/files#r148343068) with `acorn`, but I think that we should prioritise the `rollup` ecosystem and the conventions used by it, and if need be, attempt to fix the issue in `acorn` rather than here.

**Comment by Andarist** [comment]
I have not realized this was a rollup convention when I've created mentioned PR. What problem does it cause right now?

I'm not against bringing `\0` back, if you can prepare a PR for it I'd appreciate it a lot. If you do so, we'll see if tests are passing and we'll be able to merge or continue the work based on the findings.

**Comment by danez** [comment]
When we readd it, let's add a comment so it does not get removed again 😀

**Comment by NMinhNguyen** [comment]
@Andarist don’t have access to my computer right now, but will share a repro later today :) I think basically what happened was `rollup-plugin-node-resolve` didn’t give this plugin a chance to resolve `rollupPluginBabelHelpers` due to that `if` condition that I link to in my original post.

Perhaps, I’m not supposed to declare the Node resolve plugin before Babel? But I noticed that React’s Rollup configuration does the [same](https://github.com/facebook/react/blob/467b1034ce8af6807e11deb9dfeca4d4e922ed82/scripts/rollup/build.js#L207-L222), so I kinda assumed that the order was right 😅 To give you a little more context, we’re just trying to upgrade from Babel 6 to 7, and with Babel 6 we were using version 3.x of this plugin (same as React).

@danez good shout, and I might try to add an integration test to further reinforce the expected behaviour 🙂
