### ISSUE TITLE
Upgrade to babel 6

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-babel#2]
This could be easier said than done, as `whitelist` and `blacklist` are no longer supported. We either have to a) insist that people don't specify the modules transformer plugin (which is a nuisance, since it's bundled with babel-preset-es2015), or b) intercept the options object that Babel would generate for itself (from `.babelrc` etc) and remove anything that looks like that transformer.

**Comment by Victorystick** [comment]
That seems pretty painful.

**Comment by aeosynth** [comment]
you could ask babel to not bundle the commonjs transformer in the es2015 preset

**Comment by Victorystick** [comment]
@aeosynth That might just be possible. It's not as if ES modules obviously should desugar to CommonJS per default.

I suspect that Babel will want to keep the current behavior so as not to break too much code depending on this feature.

**Comment by aeosynth** [comment]
i'm sure they're open to breaking changes, given how much has broken so far xD

**Comment by aeosynth** [comment]
another option, publish your own `babel-rollup` preset that takes the es2015 preset and removes the modules transformer.

**Comment by Rich-Harris** [comment]
@aeosynth I went with that approach – have published [babel-preset-es2015-rollup](https://github.com/rollup/babel-preset-es2015-rollup). Spent a few fruitless hours trying to find more user-friendly and lower-maintenance approaches but the Babel 6 architecture isn't all that conducive to it. So Babel 6 users will need to install that preset and use it in their Babel config.

Have released it as 2.0.0 so that those of us still using Babel 5 can do `npm i rollup-plugin-babel@1`.
