### ISSUE TITLE
`require is not defined`: `require("rollupPluginBabelHelpers")` is not transformed in `4.0.0-beta.2`?

### ISSUE THREAD

**Issue by 4cm4k1** [rollup/rollup-plugin-babel#200]
Hi,
I'm coming from having used Webpack. Without `rollup-plugin-babel` this setup works great, but I can't count on users having browser support for `async`/`await`, and that's where I run into trouble. After building in prod or dev mode, I encounter the following console error:
```shell
Uncaught ReferenceError: require is not defined
    at index.js:1
    at index.js:7
```
Which points to:
```js
// node_modules/@babel/runtime/regenerator/index.js
module.exports = require("regenerator-runtime");
                 ^^^
```
Which is called by `test()` because it's an `async` function, which would need to be transformed into a generator and then use `regenerator-runtime` to work in older browsers:
```js
// index.js
async function test() {
  const user = await fetch('https://randomuser.me/api/')
  const user1 = await user.json()
  console.log('user: ', user1)
}
test()
```
Here's my `rollup.config.js`:
```js
// rollup.config.js
import uglify from 'rollup-plugin-uglify'
import babel from 'rollup-plugin-babel'
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'

const production = !process.env.ROLLUP_WATCH

export default {
  input: 'src/index.js',
  output: {
    file: 'dist/bundle.js',
    format: 'iife',
    sourcemap: true
  },
  plugins: [
    resolve(),
    commonjs({
      include: 'node_modules/**'
    }),
    babel({
      runtimeHelpers: true,
      exclude: 'node_modules/**'
    }),
    production && uglify()
  ]
}
```
Here's my `.babelrc`:
```json
// .babelrc
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false,
      "targets": {
        "browsers": ["last 2 versions"]
      }
    }]
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "helpers": false,
      "polyfill": false,
      "regenerator": true,
      "moduleName": "@babel/runtime"
    }],
    "@babel/plugin-external-helpers"
  ]
}
```
And my `package.json`:
```json
// package.json
{
  "name": "sandbox",
  "version": "1.0.0",
  "main": "index.js",
  "author": "Anthony Maki (https://anthony.codes) <4cm4k1@gmail.com>",
  "license": "MIT",
  "private": true,
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.42",
    "@babel/core": "^7.0.0-beta.42",
    "@babel/plugin-external-helpers": "^7.0.0-beta.42",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.42",
    "@babel/preset-env": "^7.0.0-beta.42",
    "npm-run-all": "^4.1.2",
    "rollup": "^0.57.1",
    "rollup-plugin-babel": "^4.0.0-beta.2",
    "rollup-plugin-commonjs": "^9.1.0",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-uglify": "^3.0.0"
  },
  "scripts": {
    "build": "rollup -c",
    "watch": "rollup -c -w",
    "dev": "npm-run-all --parallel start watch",
    "start": "serve"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0-beta.42"
  }
}
```
Because I'm running all the latest dependencies, I do get the following message about `external-helpers` being deprecated:
```shell
(!) Using "external-helpers" plugin with rollup-plugin-babel is deprecated, as it now automatically deduplicates your Babel helpers.
```
I've tried running it without the plugin with similar results. Also, I've done some config tweaking (but can't remember exactly with what) that results in the error (also `require is not defined`) pointing to a line in the produced `bundle.js`:
```js
var _asyncToGenerator = require("rollupPluginBabelHelpers").asyncToGenerator;
                        ^^^
```
Any tips, or is this a bug? Thanks!

**Comment by Andarist** [comment]
is this:
```js
// index.js
async function test() {
  const user = await fetch('https://randomuser.me/api/')
  const user1 = await user.json()
  console.log('user: ', user1)
}
test()
```
your whole project (its important - because babel might not know what type of file this is and therefore which from import/require to choose)?

Sharing a sample repository with the issue reproduced would make it for us way easier to check it out (and possibly fix or inform you what's wrong).

**Comment by 4cm4k1** [comment]
Thank you for the reply. I will post a sample repo later today. I didn't have access to my commit-signing key to push to GitHub, sorry.

**Comment by 4cm4k1** [comment]
@Andarist Sorry for the delay. Here's the example repo: https://github.com/4cm4k1/rollup-babel-example

**Comment by Andarist** [comment]
I don't know yet what's the exact problem and if this is a bug or not (or rather how this can be fixed with plugins/options), but I can confirm that it's related to what I've described before. Babel probably fails to recognize what's inside your file (module or script) because there are no import/export declarations.

It inserts `require` instead of `import` in this case and for some reason `require("\n rollupPluginBabelHelpers")` doesnt get resolved by the plugin.

If you add i.e `export default 42` it starts to work. 

Need to dig deeper into this, thanks for repro!

**Comment by Andarist** [comment]
Please try the new version, it seems that this might have been caused by some incompatibility between used babel helper & newer versions of babel beta. I've tried it on your sample repository and it seems resolved.

**Comment by 4cm4k1** [comment]
Thank you! I'll try this out today.

**Comment by 4cm4k1** [comment]
Just tried `4.0.0-beta.4` and works great! Thank you!
