### ISSUE TITLE
bundling unnecessary code with styled-jsx/babel plugin

### ISSUE THREAD

**Issue by Tomekmularczyk** [rollup/rollup-plugin-babel#202]
Hi guys,

I would like to ask you for a help. I want to have a library of components that use [style-jsx](https://github.com/zeit/styled-jsx) as an external dependency - styled-jsx library only requires to add babel plugin. However, resulting bundle consists of a whole lot of more code than necessary.

Here is [the repo with minimal configuration](https://github.com/Tomekmularczyk/react-package-rollup/tree/with-styled-jsx). 

Is there anything I can do to bundle just that component and only what's required?

**Comment by Andarist** [comment]
Extra included code looks like `prop-types`. U need to use `externals: ['prop-types']` in ur rollup's config.

**Comment by Tomekmularczyk** [comment]
This extra code wasn't prop-types actually. Anyway, I've found [help here]( https://github.com/zeit/styled-jsx/issues/159#issuecomment-379707578) (I didn't know about this issue before I created this one).

**Comment by Andarist** [comment]
Can this issue be closed then?

**Comment by Tomekmularczyk** [comment]
Yep
