### ISSUE TITLE
[QUESTION] How do I keep debugger statements?

### ISSUE THREAD

**Issue by dotnetCarpenter** [rollup/rollup-plugin-babel#203]
I have a very basic rollup setup but can't find any resources on why my `debugger` statements are removed or where I can configure _rollup-plugin-babel_ to keep them.

My entire _rollup.config.js_:

```js
// rollup.config.js
import babel from 'rollup-plugin-babel'
import resolve from 'rollup-plugin-node-resolve'
import path from 'path'

export default {
  input: path.resolve(__dirname, 'src', 'index.js'),
  output: {
    name: 'panzoom',
    file: path.resolve(__dirname, 'dist','panzoom.js'),
    format: 'umd',
    sourcemap: true
  },
  plugins: [
    resolve({
      extensions: ['.js', '.mjs'],
      modulesOnly: true
    }),
    babel({
      // only transpile our source code
      exclude: 'node_modules/**'
    })
  ]
}
```

I have the following dependencies in order to get _rollup_  and _babel_ to work - this is the minimum I could get to work. If anyone can point  to which package is removing `debugger` statements (if it isn't _rollup-plugin-babel_), I will appreciate it!

```json
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-preset-env": "^1.6.1",
    "rollup": "^0.57.1",
    "rollup-plugin-babel": "^3.0.3",
    "rollup-plugin-commonjs": "^9.1.0",
    "rollup-plugin-node-resolve": "^3.3.0"
}
```

_.babelrc_:
```json
{
  "presets": [
    ["env", {
      "modules": false
    }]
  ],
  "plugins": ["external-helpers"]
}
```

**Comment by Andarist** [comment]
are debugger statements kept in your source code?

**Comment by dotnetCarpenter** [comment]
Not sure I get your question.
 The point is that it's easier to use `debugger` statements, than wade through source files and then find the same line in the _dest_ file (as is the case of Firefox) to set a breakpoint.
The issue is that the `debugger` statements are removed from the output.

**Comment by dotnetCarpenter** [comment]
Turns out I was wrong. It works now. Not sure why it didn't work - perhaps a sync issue with my browser-sync setup.
