### ISSUE TITLE
Sourcemaps are missing the first mapping

### ISSUE THREAD

**Issue by lukeapage** [rollup/rollup-plugin-babel#21]
this doesn't happen with just rollup but with the babel plugin added it does happen.

I'm still trying to track down for sure if it is caused by babel or rollup-plugin-babel

This does not effect chrome, but it does effect using remap-istanbul.

I did some debugging that outputted the mappings for a line when it doesn't find the original mapping. It seems its the start index it cant get the original source location for because its missing the first mapping in the line.

debug Info:
```
not found { generatedLine: 3861, generatedColumn: 7 }
Mapping {
  generatedLine: 3861,
  generatedColumn: 11,
  source: 23,
  originalLine: 46,
  originalColumn: 8,
  name: null }
Mapping {
  generatedLine: 3861,
  generatedColumn: 27,
  source: 23,
  originalLine: 46,
  originalColumn: 24,
  name: null }
Mapping {
  generatedLine: 3861,
  generatedColumn: 28,
  source: 23,
  originalLine: 46,
  originalColumn: 25,
  name: null }
Mapping {
  generatedLine: 3861,
  generatedColumn: 35,
  source: 23,
  originalLine: 46,
  originalColumn: 32,
  name: null }
Mapping {
  generatedLine: 3861,
  generatedColumn: 40,
  source: 23,
  originalLine: 46,
  originalColumn: 37,
  name: null }
Mapping {
  generatedLine: 3861,
  generatedColumn: 45,
  source: 23,
  originalLine: 46,
  originalColumn: 42,
  name: null }
Mapping {
  generatedLine: 3861,
  generatedColumn: 47,
  source: 23,
  originalLine: 46,
  originalColumn: 44,
  name: null }
```
generated:
```
       if (includeScenarios.numbers !== false) {
```
original:
```
    if (includeScenarios.numbers !== false) {
```

**Comment by lukeapage** [comment]
and debugging a bit further I see that the sourcemap from babel is correct...

```
  { generatedLine: 47,
    generatedColumn: 0,
    source: 'valid-characters.js',
    originalLine: 46,
    originalColumn: 1 },
  { generatedLine: 47,
    generatedColumn: 5,
    source: 'valid-characters.js',
    originalLine: 46,
    originalColumn: 5 },
  { generatedLine: 47,
    generatedColumn: 21,
    source: 'valid-characters.js',
    originalLine: 46,
    originalColumn: 21 },
  { generatedLine: 47,
    generatedColumn: 22,
    source: 'valid-characters.js',
    originalLine: 46,
    originalColumn: 22 },
  { generatedLine: 47,
    generatedColumn: 29,
    source: 'valid-characters.js',
    originalLine: 46,
    originalColumn: 29 },
  { generatedLine: 47,
    generatedColumn: 34,
    source: 'valid-characters.js',
    originalLine: 46,
    originalColumn: 34 },
  { generatedLine: 47,
    generatedColumn: 39,
    source: 'valid-characters.js',
    originalLine: 46,
    originalColumn: 39 },
  { generatedLine: 47,
    generatedColumn: 41,
    source: 'valid-characters.js',
    originalLine: 46,
    originalColumn: 41 },
```
(the line generated by babel - the same as the output just 1 character less spaces)
```
        if (includeScenarios.numbers !== false) {
```

I see that it isn't actually this plugin causing the issue but the code in rollup that handles the sourcemap from the plugin.. it seems to be incorrectly merging the mappings from the start of the line so that we loose some mapping information that you can see babel is providing.

**Comment by lukeapage** [comment]
Let me know if you want me to re-raise on rollup/rollup

**Comment by lukeapage** [comment]
note: this does not happen if compiling all files with babel separately and then using rollup on the result. It only happens when using the plugin

note 2: the result is that my code coverage information is completely destroyed, I get 100% on almost everything.

happy to help (or try to make a test case), but it would be good to hear your thoughts.. maybe you have an idea where the problem lies from my description?

**Comment by Rich-Harris** [comment]
My hunch is that the bug is probably somewhere in [collapseSourcemaps.js](https://github.com/rollup/rollup/blob/master/src/utils/collapseSourcemaps.js) – haven't had a chance to look into it yet though

**Comment by Rich-Harris** [comment]
Struggling to reproduce this – if you could help with a test case that'd be great. I think it should be on rollup/rollup, as this plugin probably isn't to blame (it just passes the sourcemap along)

**Comment by lukeapage** [comment]
Ok I will have a go at hacking my repo down to a small testcase.

**Comment by lukeapage** [comment]
Hrmm.. now I can upgrade to 0.22.2 (0.22.1 blocked me with the other issue) I no longer reproduce the issue.

Could it have been an issue in magic-string? anyway, doesn't matter it seems fixed. If I switch back to 0.22.0 the problem comes back, if I delete node_modules and go to 0.22.2 the problem goes away..

**Comment by Rich-Harris** [comment]
Ah, that seems possible now that you mention it. Self-closing issues are the best kind :-)
