### ISSUE TITLE
Strange issue when using it after commonjs plugin

### ISSUE THREAD

**Issue by ekoeryanto** [rollup/rollup-plugin-babel#210]
`!] (commonjs plugin) SyntaxError: Unexpected token (4:22) in C:\Users\whoami\Desktop\rollup-lib\src\index.js
src\index.js (4:22)
2:
3: export default class FooComponent extends React.Component {
4:   static defaultProps = {};
                         ^
5:   state = {
6:     foo: 1,
....
`

**Comment by Andarist** [comment]
Try to reorder ur plugins, babel should come before commonjs.

**Comment by dwiyatci** [comment]
@Andarist Do you know the reasoning as to "why" the order matters here? Thought the commonjs plugin will only convert CJS to ESM before Rollup can process them... 🙄

**Comment by Andarist** [comment]
@dwiyatci yes, that's a gist - but commonjs plugin actually tries to parse your source code to determine if it's a script (commonjs) or a module (esm), so it has to be able to parse it. If you are using some non-standard syntax then it might fail if you hand it source file rather than babel output.

**Comment by dwiyatci** [comment]
@Andarist Ah, got it now. Thanks! But if I set `modules: false` in my `preset-env` options, would it be conflicting or breaking that setup again then (since Babel won't transpile the ESM module syntax to CJS)?

**Comment by nicolo-ribaudo** [comment]
You can use the `include` option of the `commonjs` plugin to apply it only to files in `node_modules` (that usually are the only ones containing CommonJS): https://github.com/rollup/plugins/tree/master/packages/commonjs#include

**Comment by dwiyatci** [comment]
@nicolo-ribaudo Gotcha. Thank youu 🙇🏻
