### ISSUE TITLE
Error after upgrade to babel v7. (with babel-plugin-rewire-exports)

### ISSUE THREAD

**Issue by dmowski** [rollup/rollup-plugin-babel#211]
I'm using the plugin-plugin-rewire-exports
https://github.com/asapach/babel-plugin-rewire-exports

Which works well with babel v7 without rollup.
And it works normally with babel v6 with rollup

When I try to connect it with babelv7 and rollup and rollup-plugin-babel.

Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information

If I delete this check, everything starts working fine.
`if ( !~check.indexOf( 'export default' ) && !~check.indexOf( 'export default Foo' ) ) { throw new Error( 'It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information' ); }`

My examples:
(Babel 7) Failed error -  https://github.com/dmowski/babel-7-with-rollup
(Babel 6) Everything is ok - https://github.com/dmowski/babel-6-with-rollup

**Comment by Andarist** [comment]
I've fixed the issue, going to make a new release in a moment.
