### ISSUE TITLE
Exclude with npm or yarn link not working

### ISSUE THREAD

**Issue by luwes** [rollup/rollup-plugin-babel#214]
The exclude filter `exclude: 'node_modules/**'` is working good when packages are installed the classic way but when using `yarn link` the `id`'s alias to the package folder not below `node_modules` making the exclude filter not work anymore.

**Comment by Andarist** [comment]
Not sure if it can be solved without breaking other cases, but if it is it should be reported in [this repo](https://github.com/rollup/rollup-pluginutils/). If you figure out how to tweak [`createFilter`](https://github.com/rollup/rollup-pluginutils/blob/a4f039b734e2c119b79e6b67ab588bcc097f7b36/src/createFilter.js#L5) I'm sure a PR would get accepted there.
