### ISSUE TITLE
Babel transform-runtime don't work correctly.

### ISSUE THREAD

**Issue by lzlu** [rollup/rollup-plugin-babel#217]
I tried to config .babelrc and rollup.config.prod.js above

```json
// .babelrc
{
  "presets": [
    ["env",{
      "modules": false
    }]
  ],
  "plugins": [
      "external-helpers",
      "transform-runtime"
  ]
}
```

```js
//rollup.config.prod.js
import resolve from 'rollup-plugin-node-resolve';
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
export default {
    input: 'src/index.js',
    output: {
      file: 'lib/bundle.min.js',
      format: 'cjs'
    },
    plugins: [
        resolve(),
        babel({
          exclude: 'node_modules/**', // only transpile our source code
          runtimeHelpers: true,
          externalHelpers: false,
        }),
        commonjs({
            include: 'node_modules/**'
        })
    ]
};
```
and this is my test file

```js
class Foo {
  method() {}
}

const bar = () => {
  console.log('bar');
}

let a = new Set();
a.set('key12',123);
console.log(a.get('key12'));
export default Foo;
```

then I run build and rollup output all babel polyfill to my _bundle.min.js_ , more than **1162** lines code, big than I expected.
the transform should work [Automatically](https://babeljs.io/docs/plugins/transform-runtime/#technical-details).
It looks like _transform-runtime_ not work correctly.
what should I config? 
Thanks.
(ps. I am so sorry for my poor English, I wish I can describe my problem. Waiting for your reply.)

**Comment by Andarist** [comment]
That's really a question for babel. Not sure what exact polyfills got added in this case - but maybe all of it was because you have used `Set` and `transform-runtime` just pulled its polyfill into ur bundle?

**Comment by adolt** [comment]
Maybe you can treat `babel-runtime` as an **external** dependency.

**Comment by savokiss** [comment]
Refer to #148, Make external like this:
```js
  external: (id) => id.indexOf('babel-runtime') === 0,
```
