### ISSUE TITLE
Issue with @babel/typescript

### ISSUE THREAD

**Issue by tobiastimm** [rollup/rollup-plugin-babel#222]
When I use `'@babel/typescript'` I need to add `.ts` and `.tsx` to my imports. Otherwise these files can't be resolved.

`src/index.ts`
```ts
export * from './components/Button/Button';
```

```sh
[!] Error: Could not resolve './components/Button/Button' from src/index.ts
```

**Comment by Andarist** [comment]
U can use `rollup-plugin-node-resolve` and its `extensions` option. This has nothing to do with `rollup-plugin-babel`
