### ISSUE TITLE
presets fail

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup-plugin-babel#23]
If `presets` is not defined I get this error
```
An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
```

Need more smart detection for more informative errors.

**Comment by Rich-Harris** [comment]
The error worked though – you're here :grinning: 

I think we need to ensure that the http://babeljs.io/docs/plugins/transform-es2015-classes/ plugin is enabled for the preflight check, since that's what helps us figure out how helpers are being treated.

**Comment by TrySound** [comment]
@Rich-Harris How do this without re resolving `.babelrc`?

**Comment by Rich-Harris** [comment]
Think we just need to change [this line](https://github.com/rollup/rollup-plugin-babel/blob/master/src/index.js#L9) to this:

```js
var check = transform( 'export default class Foo {}', assign( {}, localOpts, {
  plugins: [ 'transform-es2015-classes' ]
}).code;
```

The passed-in options are merged into the nearest `.babelrc`, IIRC
