### ISSUE TITLE
rollup-plugin-babel does not use .babelrc

### ISSUE THREAD

**Issue by charlestati** [rollup/rollup-plugin-babel#232]
Using this:

```javascript
plugins: [
  babel(), // version ^4.0.0-beta.7
],
```

I get the `Support for the experimental syntax 'objectRestSpread' isn't currently enabled`

I edited my `.babelrc` to include `@babel/plugin-proposal-object-rest-spread`: 

```
{
  "presets": [["@babel/preset-env", { "modules": false }]],
  "plugins": ["@babel/plugin-proposal-object-rest-spread"]
}
```

But it doesn't change anything unless I include it directly in `rollup-plugin-babel`'s config:

```javascript
plugins: [
  babel({
    plugins: ['@babel/plugin-proposal-object-rest-spread'],
  }),
],
```

Why isn't `rollup-plugin-babel` reading my `.babelrc`? 😪

**Comment by Andarist** [comment]
You'd have to share a repository with the issue reproduced, without it I won't be able to help you.

**Comment by Andarist** [comment]
babel@7 wont use ur local `.babelrc` config to transpile files inside `node_modules`. You can rename ur config file to `babel.config.js` - it should work.
