### ISSUE TITLE
Can't work with experimentalPreserveModules options

### ISSUE THREAD

**Issue by looch** [rollup/rollup-plugin-babel#236]
Can't work with experimentalPreserveModules options, an error is as follows:

> (node:69913) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/Users/c100ng/github/rollupTest/\u0000rollupPluginBabelHe...

**Comment by Andarist** [comment]
Could u prepare a sample repo illustratung the problem?

**Comment by Andarist** [comment]
@looch I would love to fix this problem but due to limited time resources I would need a sample repository illustrating the problem. If you can provide one I will take care of it, otherwise I won't be able to fix this any time soon and I'm forced to close this issue for now.
