### ISSUE TITLE
Please use a semver range for peerDependency

### ISSUE THREAD

**Issue by zeorin** [rollup/rollup-plugin-babel#239]
```
yarn install v1.8.0
(node:7380) ExperimentalWarning: The fs.promises API is experimental
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[---------------------------------------------------------------------------------------------------------------] 0/863(node:7380) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] 🔗  Linking dependencies...
warning " > rollup-plugin-babel@3.0.7" has unmet peer dependency "babel-core@6".
[5/5] 📃  Building fresh packages...
✨  Done in 2.99s.
```
```
yarn list v1.8.0
(node:13482) ExperimentalWarning: The fs.promises API is experimental
└─ babel-core@6.26.3
✨  Done in 0.59s.
```
I'm assuming that any 6.x babel-core version ought to work with 3.0.7. Everything _works_, but there's the annoying warning message. I try to remove all warnings so that there's a high signal-to-noise ratio in my terminal output.

Please consider using an appropriate semver range for specifying the peerDependency.

**Comment by Andarist** [comment]
PRs are welcome here 😉

**Comment by loganfsmyth** [comment]
Is this an issue with Yarn somehow? `6` should work in this context, according to http://jubianchi.github.io/semver-check/

<img width="745" alt="screen shot 2018-08-24 at 2 40 45 pm" src="https://user-images.githubusercontent.com/132260/44609265-d172ad80-a7ab-11e8-9c4d-be0a0efebdfe.png">

**Comment by nickmccurdy** [comment]
4.0.2 fixes it.

**Comment by Andarist** [comment]
Seems it is resolved, closing the issue. Feel free to open new one if you have more questions.
