### ISSUE TITLE
I get an error at my TypeScript-React-library with 4.0.2

### ISSUE THREAD

**Issue by PutziSan** [rollup/rollup-plugin-babel#241]
On Windows 10 with node v8.11.3 I get following error when using `rollup-plugin-babel@4.0.2`

![image](https://user-images.githubusercontent.com/13392042/44713363-43503d00-aab3-11e8-8828-c6f00378ec78.png)

with `4.0.0-beta.8` it builds without any errors.

You can see the configs online at github: [babel.config.js](https://github.com/PutziSan/formik-fields/blob/master/babel.config.js) + [rollup.config.js](https://github.com/PutziSan/formik-fields/blob/master/rollup.config.js)

**Comment by Andarist** [comment]
You probably have to add `.ts` as valid extension to the config passed to rollup-plugin-babel.
```js
extensions: ['.ts', '.tsx', '.js', '.jsx']
```

I might take a look later if we could do this automatically, but I'm not sure how safe it is to assume those things.

**Comment by PutziSan** [comment]
Yep, that fixes the problem. Thanks!

I don't think you have to recognize this automatically, but a small section in the documentation would be good. You might also want to add a hint in the changelog file that this option could break existing configurations. (If you read it correctly, you actually come to the same conclusion, but it is currently up to the user to draw this conclusion ;) )

**Comment by Andarist** [comment]
Right. Handling only default extensions + configurable option for it was part of 4.0.0 release - https://github.com/rollup/rollup-plugin-babel/commit/9f93edacad183cd831ee128cb274da1b5c10e7e0 . It was actually a fix for other issues, would be cool to somehow autodetect if you want to handle TS with babel, but I haven't yet thought it through and not sure how safe is to do that.
