### ISSUE TITLE
Imported modules that have a package.json beside or above them will not be transpiled by babel plugin

### ISSUE THREAD

**Issue by blakemann** [rollup/rollup-plugin-babel#242]
# Expected Behaviour:
- Babel plugin should transpile all code in bundle / chunks

# Actual Behaviour:
- Some modules files will not be transpiled within the bundle if there is a `package.json` file in the same directory, or a parent directory, of the module to be imported.

# Minimal Example:

- [dependency-transpile-test.zip](https://github.com/rollup/rollup-plugin-babel/files/2328475/dependency-transpile-test.zip)

# Summary of Example:

```javascript
// src/test.js

import { addSpaces } from '../dependencies/src/dependency.js';

class SayHello {

    constructor(){
        let string = 'Hello World';
        console.log(addSpaces(string));
    }

}

new SayHello();
```
```javascript
// dependencies/src/dependency.js

export function addSpaces(x){
    let y = '';
    x.split('').forEach((letter) => {
        y = `${y} ${letter}`;
    });
    return y;
}
```
```javascript
// dependencies/package.json

{} // file doesn't even need to have anything in it, just needs to exist and be valid json
```
```javascript
// rollup.config.js

import babel from 'rollup-plugin-babel';

export default {
    input: 'src/test.js',
    output: {
        file: 'dist/test.js',
        format: 'esm'
    },
    plugins: [
        babel()
    ]
}
```

# Resulting Bundled Code:
**_(result of running rollup with `esm` format and `babel` plugin)_**

```javascript
// dist/test.js

function _classCallCheck(instance, Constructor) {
  if (!(instance instanceof Constructor)) {
    throw new TypeError("Cannot call a class as a function");
  }
}

function addSpaces(x) {
  let y = '';
  x.split('').forEach(letter => {
    y = `${y} ${letter}`;
  });
  return y;
}

var SayHello = function SayHello() {
  _classCallCheck(this, SayHello);

  var string = 'Hello World';
  console.log(addSpaces(string));
};

new SayHello();
```

Notice how the `addSpaces` function does not get transpiled. If you simply remove the `package.json` file from the `dependencies` directory, and re-bundle, the function will be correctly transpiled.

**Comment by Andarist** [comment]
This is a new babel 7 behaviour - https://deploy-preview-1787--babel.netlify.com/docs/en/next/config-files#file-relative-configuration

You need to use `babelrcRoots` option or project-level `babel.config.js`

**Comment by blakemann** [comment]
@Andarist thank you, that has solved the problem for me!
