### ISSUE TITLE
Error: Runtime helpers are not enabled

### ISSUE THREAD

**Issue by QingLeiLi** [rollup/rollup-plugin-babel#246]
```
// babel.config.js
module.exports = {
    "presets": [
        ["@babel/preset-env", {
            "debug": true,
            "useBuiltIns": 'usage'
        }]
    ],
    "plugins": ["@babel/plugin-transform-runtime"]
}
```
I`m using babel7, config like above, and get an error with rollup
```
[!] (babel plugin) Error: Runtime helpers are not enabled. Either exclude the transform-runtime Babel plugin or pass the `runtimeHelpers: true` option. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
```
I think it case by plugin does not compatible with babel7, any idea?

package
```
"devDependencies": {
    "@babel/core": "^7.0.0",
    "glob": "^7.1.3",
    "rollup": "^0.65.0",
    "rollup-plugin-babel": "^4.0.2",
    "rollup-plugin-commonjs": "^9.1.6",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-uglify": "^5.0.2",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-env": "^7.0.0"
  }
```

**Comment by Andarist** [comment]
The error literally tells you what the problem is and how to solve it, please pass `runtimeHelpers: true` to your `rollup-plugin-babel` options like in example [here](https://github.com/drcmda/react-spring/blob/f07a457a62df9b95eaaa0535aee738721c145f05/rollup.config.js#L20)

**Comment by QingLeiLi** [comment]
My bad, I misunderstanding the word, sorry about that.
I pass the option, then everything work fine.

**Comment by ranquild** [comment]
For everyone coming here from goggle, using `rollup-plugin-auto-external` makes `@babel/runtime` bundled. Solution is to use custom external function from @Andarist .
