### ISSUE TITLE
An unexpected situation arose

### ISSUE THREAD

**Issue by Fred2MTL** [rollup/rollup-plugin-babel#247]
Hi 
I update my building stack from Babel 6 to 7, as following:
`	"devDependencies": {"@babel/cli": "^7.0.0",
		"@babel/core": "^7.0.0",
		"@babel/plugin-external-helpers": "^7.0.0",
		"@babel/plugin-proposal-class-properties": "^7.0.0",
		"@babel/plugin-proposal-decorators": "^7.0.0",
		"@babel/plugin-proposal-do-expressions": "^7.0.0",
		"@babel/plugin-proposal-export-default-from": "^7.0.0",
		"@babel/plugin-proposal-export-namespace-from": "^7.0.0",
		"@babel/plugin-proposal-function-bind": "^7.0.0",
		"@babel/plugin-proposal-function-sent": "^7.0.0",
		"@babel/plugin-proposal-json-strings": "^7.0.0",
		"@babel/plugin-proposal-logical-assignment-operators": "^7.0.0",
		"@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0",
		"@babel/plugin-proposal-numeric-separator": "^7.0.0",
		"@babel/plugin-proposal-optional-chaining": "^7.0.0",
		"@babel/plugin-proposal-pipeline-operator": "^7.0.0",
		"@babel/plugin-proposal-throw-expressions": "^7.0.0",
		"@babel/plugin-syntax-dynamic-import": "^7.0.0",
		"@babel/plugin-syntax-import-meta": "^7.0.0",
		"@babel/preset-env": "^7.0.0",
		"@babel/preset-react": "^7.0.0",
		"babel-eslint": "^9.0.0",
		"babel-plugin-transform-decorators-legacy": "^1.3.5",
		"eslint": "^5.5.0",
		"eslint-plugin-react": "^7.11.1",
		"gulp": "^4.0.0",
		"gulp-clean": "^0.4.0",
		"rollup": "^0.65.0",
		"rollup-plugin-babel": "@latest",
		"rollup-plugin-commonjs": "^9.1.6",
		"rollup-plugin-eslint": "^5.0.0",
		"rollup-plugin-json": "^3.0.0",
		"rollup-plugin-node-resolve": "^3.3.0",
		"rollup-plugin-replace": "^2.0.0",
		"rollup-plugin-terser": "^2.0.2"`

The build fails now: 
`[05:49:37] Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
    at error (/.../node_modules/rollup/dist/rollup.js:3438:30)
    at Object.error (/.../node_modules/rollup/dist/rollup.js:21120:17)
    at .../node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:72:9
    at Object.transform$1 (.../node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:174:18)
    at /.../node_modules/rollup/dist/rollup.js:20831:25
    at process._tickCallback (internal/process/next_tick.js:68:7)`

How can i provide more information ?

Thanks in advance

Fred

**Comment by Fred2MTL** [comment]
@Andarist 
It works better with v4.0.3-0, now. Thanks
Here is my configuration
`"@babel/cli": "^7.0.0",
		"@babel/core": "^7.0.0",
		"@babel/plugin-external-helpers": "^7.0.0",
		"@babel/plugin-proposal-class-properties": "^7.0.0",
		"@babel/plugin-proposal-decorators": "^7.0.0",
		"@babel/plugin-proposal-do-expressions": "^7.0.0",
		"@babel/plugin-proposal-export-default-from": "^7.0.0",
		"@babel/plugin-proposal-export-namespace-from": "^7.0.0",
		"@babel/plugin-proposal-function-bind": "^7.0.0",
		"@babel/plugin-proposal-function-sent": "^7.0.0",
		"@babel/plugin-proposal-json-strings": "^7.0.0",
		"@babel/plugin-proposal-logical-assignment-operators": "^7.0.0",
		"@babel/plugin-proposal-nullish-coalescing-operator": "^7.0.0",
		"@babel/plugin-proposal-numeric-separator": "^7.0.0",
		"@babel/plugin-proposal-optional-chaining": "^7.0.0",
		"@babel/plugin-proposal-pipeline-operator": "^7.0.0",
		"@babel/plugin-proposal-throw-expressions": "^7.0.0",
		"@babel/plugin-syntax-dynamic-import": "^7.0.0",
		"@babel/plugin-syntax-import-meta": "^7.0.0",
		"@babel/preset-env": "^7.0.0",
		"@babel/preset-react": "^7.0.0",
		"babel-eslint": "^9.0.0",
		"babel-plugin-transform-decorators-legacy": "^1.3.5",
		"eslint": "^5.5.0",
		"eslint-plugin-react": "^7.11.1",
		"gulp": "^4.0.0",
		"gulp-clean": "^0.4.0",
		"rollup": "^0.65.0",
		"rollup-plugin-babel": "^4.0.3-0",
		"rollup-plugin-commonjs": "^9.1.6",
		"rollup-plugin-eslint": "^5.0.0",
		"rollup-plugin-json": "^3.0.0",
		"rollup-plugin-node-resolve": "^3.3.0",
		"rollup-plugin-replace": "^2.0.0",
		"rollup-plugin-terser": "^2.0.2"`
Here is my gulp/rollup task:
`gulp.task('build-part', async ()=>{
	const   oTargetPath = applicationConfiguration.target,
			oModules = applicationConfiguration.modules;
	const bundle = await rollup.rollup({
		input: oModules.path + '/' + oModules.entry,
		plugins: [
			rollupJson(),
			rollupBabel({exclude: 'node_modules/**'}),
			rollupNodeResolve(),
			rollupReplace({'process.env.NODE_ENV': JSON.stringify('production')}),
			rollupCommonJS({'namedExports': {
					'node_modules/react/index.js': ['cloneElement', 'createElement', 'PropTypes', 'PureComponent','Children', 'Component', 'isValidElement', 'Fragment'],
					'node_modules/react-dom/index.js': ['createPortal', 'findDOMNode', 'unstable_batchedUpdates']
					}})
			//rollupTerser.terser()
		]
	});

	await bundle.write({
		format: 'umd', name: 'panelManagement-Admin',sourcemap: true,
		file: `${oTargetPath}/assets/js/Module.min.js`,
	});

});`

**Comment by nicolo-ribaudo** [comment]
(OT) @Fred2MTL You can rap your code using
\`\`\`
... code ...
\`\`\`

**Comment by Fred2MTL** [comment]
@nicolo-ribaudo 
Great. Thanks. Seems better ;-)

**Comment by Andarist** [comment]
From what I understand you have resolved your issue, if that's not the case please respond back with more details about your case. Going to release that `4.0.3-0` as `4.0.3` now.
