### ISSUE TITLE
can not work when i upgrade

### ISSUE THREAD

**Issue by jasonChen1982** [rollup/rollup-plugin-babel#248]
I use rollup-plugin-babel@4.0.3 and babel@7 and other deps, but it can not work and log an error like the following:
`Cannot find module 'babel-plugin-external-helpers'`
and I have not use `babel-plugin-external-helpers` in anywhere

**Comment by jasonChen1982** [comment]
I use rollup API directly, and the config have not `external-helpers`

**Comment by Andarist** [comment]
then I would suspect that some of ur babelrc has `external-helpers` in it

**Comment by jasonChen1982** [comment]
no babelrc

**Comment by Andarist** [comment]
Without you sharing a repository with the issue reproduced in it I won't be help you.

**Comment by nicolo-ribaudo** [comment]
Can you share the full stack trace of the error?

**Comment by jasonChen1982** [comment]
oh, I know what happens, thanks and sorry about my fool mistake.
