### ISSUE TITLE
Module only exporting default when module contains mixed default and named exports

### ISSUE THREAD

**Issue by pgraham** [rollup/rollup-plugin-babel#258]
Not sure if this is the right place for this but here goes:

I'm trying to bundle compiled typescript through rollup + rollup-plugin-babel. One of my modules has a dependency on _redux-saga_. The compiled typescript for this module looks like:

``` js
// ...
const redux_saga_1 = require("redux-saga");      // <--- LOADED HERE
//...
const sagaMw = redux_saga_1.default();             // <-- USE DEFAULT EXPORT HERE
```

After bundling this is transformed to:

``` js
// ...
var redux_saga_1 = ( es$1 && sagaMiddlewareFactory ) || es$1;
// ...
var sagaMw = redux_saga_1.default();
```

When I try and run this code I get an error: `Uncaught TypeError: redux_saga_1.default is not a function`

The problem is that the bundled code for _redux-saga_ looks like:

```
function sagaMiddlewareFactory() { ... }
// ...
var es$1 = /*#__PURE__*/Object.freeze({
    default: sagaMiddlewareFactory,
    // ...
});
```

So `redux_saga_1` is getting assigned to be the function `sagaMiddlewareFactory` instead of the object `es$1`.

My rollup config file looks like this:

```
import resolve from 'rollup-plugin-node-resolve'
import cjs from 'rollup-plugin-commonjs'
import babel from 'rollup-plugin-babel'
import replace from 'rollup-plugin-replace'
import uglify from 'rollup-plugin-uglify'
import copy from 'rollup-plugin-copy'

const env = process.env.NODE_ENV || 'development'
const isProd = env === 'production'

const webDir = isProd ? 'build/work/web' : 'build/work/src/web'

export default {
  input: `${webDir}/js/main.js`,
  output: {
    file: `${webDir}/app.js`,
    format: 'iife',
    name: 'zeptech',
    sourcemap: !isProd
  },
  plugins: [
    copy({
      verbose: true,
      'src/web/index.html': `${webDir}/index.html`,
      'src/web/img': `${webDir}/img`
    }),
    resolve({
      browser: true,
      jsnext: false,
      extensions: ['.js', '.json', '.jsx']
    }),
    replace({ 'process.env.NODE_ENV': JSON.stringify(env) }),
    cjs(),
    babel({
      exclude: 'node_modules/**'
    }),
    isProd && uglify()
  ],
  watch: {
    chokidar: {
      usePolling: true
    }
  }
}
```

Not sure how to address this and am looking for clues as to how to consume a library that provides mixed default and named exports?

**Comment by Andarist** [comment]
That's probably a problem between TS output & rollup-plugin-commonjs logic. To some extent you might find out more about why this might happen in this issue - https://github.com/webpack/webpack/issues/7973 .

Either way I would recommend to output ESM instead of CJS from TS and consume that with rollup as it will "just work", but also yield better results in terms of final output size.

**Comment by pgraham** [comment]
Thanks for the reply. I will investigate that bug, but am wondering, am I going to find that what I want to do is just not possible?

I would like to the typescript module output format as CJS since I also have Typescript sources that are targeted to a Node environment.

Being to include all of my sources in the tsconfig.json works way better with my editor (VIM) since the typescript support doesn't let me configure multiple tsconfig.json files.

I guess if this approach isn't going to work I can create a separate tsconfig.json that are used for the build and keep my all-in-one default tsconfig.json for editor support.

**Comment by Andarist** [comment]
If I understand everything correctly you need to:
- either build with tsc 2 times, to cjs and esm formats separately, use cjs files for node (main in package.json), treat esm output and temp and consume it with rollup (if your package is isomorphic - could be used in both node and in browsers - then distribute ur esm files as module in package.json)
- or consume ur original TS files with rollup (authored in ESM format)
