### ISSUE TITLE
Generated code is not transpiled by rollup-plugin-babel to ES5 with vue plugin

### ISSUE THREAD

**Issue by cloudever** [rollup/rollup-plugin-babel#260]
### Expected behavior
Keyword `const` should be transpiled to `var` because I've applied `.browserslistrc` with `ie 9` for Babel 7.
It seems to be that code from `vue-component-compiler` is not transpiled to ES5 partially.

https://github.com/vuejs/vue-component-compiler/blob/afa1cd440123e2e0c195908c1e15935273ac64a9/src/assembler.ts#L304-L307

```json
"rollup-plugin-babel": "^4.0.3",
"rollup-plugin-vue": "^4.3.2",
```

### Actual behavior
I get following code that contains `const` not `var`!
```js
	var __vue_staticRenderFns__ = [];
	__vue_render__._withStripped = true;

	  /* style */
	  const __vue_inject_styles__ = undefined;
	  /* scoped */
	  const __vue_scope_id__ = undefined;
	  /* module identifier */
	  const __vue_module_identifier__ = undefined;
	  /* functional template */
	  const __vue_is_functional_template__ = false;
	  /* component normalizer */
	  function __vue_normalize__(
	    template, style, script$$1,
	    scope, functional, moduleIdentifier,
	    createInjector, createInjectorSSR
	  ) {
	    const component = (typeof script$$1 === 'function' ? script$$1.options : script$$1) || {};
```

### Steps to reproduce the behavior
Create babel.config.js
```js
module.exports = (api) => {
  api.cache(api.env('development'));

  const presets = [
    ['@babel/preset-env', {
      modules: false,
      useBuiltIns: false,
      forceAllTransforms: true,
    }],
  ];

  const plugins = [
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-object-rest-spread',
    ['@babel/plugin-transform-runtime', {
      corejs: 2,
      helpers: true,
      regenerator: false,
    }],
  ];

  return {
    presets,
    plugins,
  };
};

```

Apply plugins

```js
export default () => [
  vue({
    compileTemplate: true,
    css: false,
  }),
  babel({
    exclude: [/\/core-js\//],
    runtimeHelpers: true,
  }),
  css(),
  replace({
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
  }),
  resolve(),
  commonjs(),
].filter(Boolean);

```
And .browserslistrc
```
> 1%
last 2 versions
ie 9
```

**Comment by Andarist** [comment]
From what I remember babel ignores `node_modules` by default now, so you need to explicitly ask it to transpile them.

**Comment by loganfsmyth** [comment]
Are the files `.vue`? If so, you need to tell the plugin to process those.

Not related to your question, but FYI `api.cache(api.env('development'));` makes no sense. What that is saying is, re-evaluate your `module.exports` config function and every preset/plugin it references, for every single file, when doing a production build. That's essentially just making your production builds slower for no reason.

**Comment by cloudever** [comment]
> Are the files `.vue`? If so, you need to tell the plugin to process those.
> 
> Not related to your question, but FYI `api.cache(api.env('development'));` makes no sense. What that is saying is, re-evaluate your `module.exports` config function and every preset/plugin it references, for every single file, when doing a non-development build. That's essentially just making your production builds slower for no reason.

Babel 7.1.2 force me to add api.cache expression

**Comment by loganfsmyth** [comment]
Fair. All you need is `api.cache(true)` though. No need to call `api.env('development')`. I'll see what I can do to make that clearer.

**Comment by ghettovoice** [comment]
Try to add `extensions` option to rollup-plugin-babel options:

```js
// plugins 
...
babel({
  runtimeHelpers: true,
  sourceMap: true,
  extensions: ['.js', '.jsx', '.es6', '.es', '.mjs', '.vue'],
}),
...
```

I had the same issue after upgrade to the latest versions of rollup-plugin-vue, rollup-plugin-babel & etc.

**Comment by cloudever** [comment]
@ghettovoice Did the trick thank's

**Comment by fubangfu** [comment]
> @cloudever 尝试将`extensions`选项添加到汇总-babel选项：
> 
> ```js
> //插件
> ... 
> 巴贝尔（{
>   runtimeHelpers： 真，
>   sourceMap： 真，
>   扩展： [ '的.js '， ' .jsx '， ' .es6 '， ' .ES '， ' .mjs '， ' .vue ' ] ，
> }）， ...
> ```
> 
> 升级到最新版本的rollup-plugin-vue，rollup-plugin-babel等之后，我遇到了同样的问题
> ，此选项为我解决了这个问题。
[!] (plugin babel) SyntaxError: F:\Workspace\js\vue-ts-1\src\views\system-setup\sys-revenue-expense.vue: Unexpected token (3:16)

  1 | <template>
  2 |     <div id="app" class="view">
> 3 |         <button @click="supperSearch">1</button>
    |                 ^
  4 |         <button @click="fullSearch">2</button>
  5 |         <button @click="change(sre.page.pageNo+1)">3</button>
  6 |         <children>
src\views\system-setup\sys-revenue-expense.vue (3:16)

**Comment by fubangfu** [comment]
> @cloudever try to add `extensions` option to rollup-plugin-babel options:
> 
> ```js
> // plugins 
> ...
> babel({
>   runtimeHelpers: true,
>   sourceMap: true,
>   extensions: ['.js', '.jsx', '.es6', '.es', '.mjs', '.vue'],
> }),
> ...
> ```
> 
> I had the same issue after upgrade to the latest versions of rollup-plugin-vue, rollup-plugin-babel & etc.
> and this options resolved it for me.

[!] (plugin babel) SyntaxError: F:\Workspace\js\vue-ts-1\src\views\system-setup\sys-revenue-expense.vue: Unexpected token (3:16)

  1 | <template>
  2 |     <div id="app" class="view">
> 3 |         <button @click="supperSearch">1</button>
    |                 ^
  4 |         <button @click="fullSearch">2</button>
  5 |         <button @click="change(sre.page.pageNo+1)">3</button>
  6 |         <children>
src\views\system-setup\sys-revenue-expense.vue (3:16)
