### ISSUE TITLE
can't use @babel/preset-typescript

### ISSUE THREAD

**Issue by Tomekmularczyk** [rollup/rollup-plugin-babel#261]
Hi and thanks for the plugin,

I want to use typescript so I thought it will be as straightforward as adding @babel/plugin-typescript to the .babelrc but this somehow doesn't strip the types from the file. I wonder why this happens and if I can fix it or do I have to use something like rollup-plugin-typescript2.

Here is how I tried to get it working - https://github.com/Tomekmularczyk/react-package-rollup/tree/with-typescript

P.S Also, I don't understand [WHY rollup-plugin-typescript](https://github.com/rollup/rollup-plugin-typescript#why) section points to this package.

**Comment by Tomekmularczyk** [comment]
@Andarist thanks! I also found a #255 meanwhile and now it works.

About the PR... I could make it, but I don't know enough details. I'm still confused why what is pointed out in the [#why](https://github.com/rollup/rollup-plugin-babel#why)-section is the reason for the rollup-plugin-typescript package. Is it about performance or some additional configuration?

**Comment by Andarist** [comment]
I think it's just about config complexity - kinda easier to have a single tool which combines multiple other tools (with plugins) to create a final output from the raw input rather than creating carefully a pipeline from those tools where each gets intermediate results.
