### ISSUE TITLE
Other plugins can't access rollupPluginBabelHelpers

### ISSUE THREAD

**Issue by luwes** [rollup/rollup-plugin-babel#265]
Code added by the babel helpers should be accessible by other plugins if needed.
We have a case where `Symbol` needs to be polyfilled, which is done by 
https://github.com/rollup/rollup-plugin-inject

Babel is adding this helper for example:
```js
function _iterableToArray(iter) {
  if (Symbol.iterator in Object(iter) || Object.prototype.toString.call(iter) === "[object Arguments]") return Array.from(iter);
}
```

This plugin sets the id of the helper to `\u0000rollupPluginBabelHelpers` which makes it automatically filtered out if the plugin uses 
https://github.com/rollup/rollup-pluginutils/blob/master/src/createFilter.js#L13

Related issues:
https://github.com/rollup/rollup-plugin-inject/issues/20
https://github.com/rollup/rollup-plugin-babel/issues/197

**Comment by Andarist** [comment]
Thanks for the report - I've responded back in the linked issue of rollup-plugin-inject.
