### ISSUE TITLE
PreflightCheck Error

### ISSUE THREAD

**Issue by zsky** [rollup/rollup-plugin-babel#267]
The code below emitted a error, because transpiled code with babel had no matching condition
```js
if (check.match(/\/helpers\/(esm\/)?inherits/)) helpers = RUNTIME;
else if (~check.indexOf('function _inherits')) helpers = INLINE;
else if (~check.indexOf('babelHelpers')) helpers = EXTERNAL;
else {
	ctx.error(UNEXPECTED_ERROR);
}
```
babel version:  7.0.0-beta.47
the output code was 
```js
import _classCallCheck from "/path/to/node_modules/@babel/runtime/helpers/builtin/es6/classCallCheck";
import _inherits from "/path/to/node_modules/@babel/runtime/helpers/builtin/es6/inherits";
import _possibleConstructorReturn from "/path/to/node_modules/@babel/runtime/helpers/builtin/es6/possibleConstructorReturn";
import _getPrototypeOf from "/path/to/node_modules/@babel/runtime/helpers/builtin/es6/getPrototypeOf";

var Foo =
/*#__PURE__*/
function (_Bar) {
  function Foo() {
    _classCallCheck(this, Foo);

    return _possibleConstructorReturn(this, _getPrototypeOf(Foo).apply(this, arguments));
  }

  _inherits(Foo, _Bar);

  return Foo;
}(Bar);

;
export default Foo;
```

I tried babel 7.1.2, also got error

**Comment by Andarist** [comment]
Could u paste in your rollup & babel configs?

**Comment by Andarist** [comment]
Could you file an issue (or check if there is any already about it) in vue-cli repo? They have a little bit outdated dependencies - https://github.com/vuejs/vue-cli/blob/528c46507a21b76f12bc416d98f9b04c0076cb50/packages/%40vue/babel-preset-app/package.json#L24-L30

For the time being it seems that you should downgrade your rollup-plugin-babel to 4.0.0-beta.7

**Comment by zsky** [comment]
They had upgraded recently: [https://github.com/vuejs/vue-cli/pull/2642](https://github.com/vuejs/vue-cli/pull/2642)
But even if I upgraded the babel, I still have this error. [https://github.com/rollup/rollup-plugin-babel/issues/268](https://github.com/rollup/rollup-plugin-babel/issues/268) said preflightCheck will be removed，how long will it takes?

**Comment by Andarist** [comment]
Could u prepare a repro case? What kind of an error do you see? What is the output code?

**Comment by zsky** [comment]
I made a minimal repo to reproduce:
```sh
git clone git@github.com:zsky/rollup-plugin-babel-issue267.git
cd rollup-plugin-babel-issue267
npm i
npm run build
```
Then outputed a error:
```
(babel plugin) Error: An unexpected situation arose.
```
I logged the code, the `_inherits`:
```js
import _inherits from "@babel/runtime/helpers/es6/inherits";
```

**Comment by Andarist** [comment]
The installed @vue/babel-preset-app@3.0.5 has still outdated babel dependencies.

**Comment by zsky** [comment]
I changed the babel config, set  [useESModules](https://babeljs.io/docs/en/babel-plugin-transform-runtime#useesmodules) false, solved my problem.
