### ISSUE TITLE
babel-preset-es2015-rollup versioning problem

### ISSUE THREAD

**Issue by qgustavor** [rollup/rollup-plugin-babel#27]
The current version of babel-preset-es2015-rollup is 1.0.0 and it's based on babel-preset-es2015 6.1.2, so it's not updated as the latest version available is 6.3.13. Currently, in order to use the updated package, I'm loading babel-preset-es2015 and manually disabling the commonjs plugin.

What can be done to install an specific version of babel-preset-es2015 adapted to rollup?

**Comment by Rich-Harris** [comment]
That's very odd – 6.3.13 should satisfy the existing semver constraint. I've just tried installing the latest version of this, and these are the versions I got:

```bash
babel-preset-es2015-rollup@1.0.0 node_modules/babel-preset-es2015-rollup
├── require-relative@0.8.7
├── babel-plugin-external-helpers-2@6.3.13 (babel-runtime@5.8.34)
└── babel-preset-es2015@6.3.13 (babel-plugin-transform-es2015-computed-properties@6.3.13, babel-plugin-transform-es2015-arrow-functions@6.3.13, babel-plugin-transform-es2015-template-literals@6.3.13, babel-plugin-transform-es2015-spread@6.3.14, babel-plugin-transform-es2015-destructuring@6.3.15, babel-plugin-transform-es2015-for-of@6.3.13, babel-plugin-transform-es2015-unicode-regex@6.3.13, babel-plugin-transform-es2015-literals@6.3.13, babel-plugin-transform-es2015-typeof-symbol@6.3.13, babel-plugin-check-es2015-constants@6.3.13, babel-plugin-transform-es2015-block-scoped-functions@6.3.13, babel-plugin-transform-es2015-sticky-regex@6.3.13, babel-plugin-transform-es2015-function-name@6.3.21, babel-plugin-transform-es2015-modules-commonjs@6.3.16, babel-plugin-transform-es2015-shorthand-properties@6.3.13, babel-plugin-transform-es2015-object-super@6.3.13, babel-plugin-transform-es2015-parameters@6.3.26, babel-plugin-transform-es2015-block-scoping@6.3.13, babel-plugin-transform-es2015-classes@6.3.15, babel-plugin-transform-regenerator@6.3.26)
```

What happens if you `rm -rf node_modules && npm i`? (If you're on npm 3, trashing the entire `node_modules` folder appears to be the most efficient way to update as far as I can tell, unfortunately)

**Comment by qgustavor** [comment]
I will see what went wrong here then report you when I find it out.
2016/01/04 20:54 "Rich Harris" <notifications@github.com>:

**Comment by eventualbuddha** [comment]
@qgustavor did you figure it out? I'd like to close this out if there's a resolution.

**Comment by qgustavor** [comment]
I don't know why but it's working now.
2016/01/16 13:37 "Brian Donovan" <notifications@github.com>:

**Comment by eventualbuddha** [comment]
If it comes up again let us know!
