### ISSUE TITLE
.babelrc or babel.config.js

### ISSUE THREAD

**Issue by kopax** [rollup/rollup-plugin-babel#273]
Dear everyone, I am a user of the v3 of this plugin.
We'd like to upgrade babel from 6 to 7, and we need to upgrade this module from v3 to v4.

The v4 doc state that the `.babelrc` file is generally the right place to put your configuration, while babel 7 state that the config file should be used.

Any information will be taken so I can understand this. I am in the process of removing by default the `.babelrc` from all our bundle/app

**Comment by loganfsmyth** [comment]
> while babel 7 state that the config file should be used.

I don't think that's accurate, you can still use `.babelrc` files with Babel 7 too, it really just depends on what you want to do. Have you read through https://babeljs.io/docs/en/config-files?

**Comment by kopax** [comment]
From your link, read : https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading

> Given that, it may be more desirable to rename the `.babelrc` to be a project-wide ["babel.config.js"](https://babeljs.io/docs/en/config-files#project-wide-configuration).

We rather switch to the new model, do we **need** to use `.babelrc` for migrating this module?

**Comment by Andarist** [comment]
Depending on your directory structure you might not have to change those options at all. If babel won't be able to find your babel.config.js then just point to it with `configFile` option. Other than that you might consider using `babelrc: false` - just to be sure that the only config that you are using is that single babel.config.js

**Comment by Andarist** [comment]
I dont think there is any actionable point here right now, closing the issue. Feel free to open new one if you have more questions.

**Comment by MwumLi** [comment]
babel 7 provide programmatic options `configfile`, which default is `${root}/babel.config.js`, https://babeljs.io/docs/en/options#configfile
