### ISSUE TITLE
typescript + rollup-plugin-babel does not transform

### ISSUE THREAD

**Issue by AllNamesRTaken** [rollup/rollup-plugin-babel#274]
Hi,
I've been failing to have my rollup of typescript to work with babel. Just running babel through npx works fine but the rollup-plugin-babel doesn't seem to find the config files?
my rollup.config.js:

    import typescript from 'rollup-plugin-typescript';
    import babel from 'rollup-plugin-babel';

    var plugins = [
        typescript(/*{ plugin options }*/),
        babel({
            exclude: 'node_modules/**',
        }),
    ];

    export default [{
        input: 'src/index.ts',
        plugins,
        output: {
            file: 'dist/index.js',
            format: 'iife',
            name: 'whatever',
            sourcemap: true,
        }
    },
    ];

.babelrc

    {
        "presets": [
            "@babel/preset-env"
        ]
    }

With this setup babel does not complain but really does nothing to my code as well.

I have tried adding a babel.config.js to root:

    module.exports = function () {
        const presets = ["@babel/preset-env"];
        //const plugins = [ ... ];

        return {
            presets,
            //   plugins
        };
    }

But no change. Like I said, babel seem to work on its own.

Is this a bug or simply me not knowing right from left?

**Comment by Andarist** [comment]
You would have to share a repository with the issue reproduced to get help with this one

**Comment by AllNamesRTaken** [comment]
[lab repo](https://github.com/AllNamesRTaken/rollup-lab)
running rollup -c will crash in the uglify plugin since the ```let``` is not transpiled

**Comment by Andarist** [comment]
You need to configure extensions which should be transpiled by babel - by default it doesnt handle `.ts` files.

Do this:
```js
    babel({
        exclude: 'node_modules/**',
        extensions: ['.js', '.ts'],
    }),
```

**Comment by AllNamesRTaken** [comment]
But I am running rollup-plugin-typescript before that to let tsc transpile it.
Shouldn't that let the babel plugin work with js?

**Comment by AllNamesRTaken** [comment]
Thanks solved it. I also had change my config to:

    module.exports = function(api) {
        api.cache(true)
        ...

Close this please.

**Comment by slavafomin** [comment]
Hello!

So, @Andarist are you telling that `rollup-plugin-babel` will automatically handle `.ts` files by passing them through the TypeScript compiler? If so, how do you specify path to the `tsconfig.json`?

Thanks.
