### ISSUE TITLE
Expose custom babel loader builder

### ISSUE THREAD

**Issue by esphen** [rollup/rollup-plugin-babel#275]
Hello :wave:

Before I go on to the suggestion, I would like to thank the Rollup team for your excellent work. It's really amazing to see you pushing the envelope on build systems. Keep it up! 💯

`rollup-plugin-babel` has a lot of great features, but there is one we would love to see added. `babel-loader` exposes a [custom loader builder](https://github.com/babel/babel-loader/#customized-loader) to enable developers to build a custom loader and add their own handling of Babel's configuration, for example change or override it. It would be great to have a similar feature in `rollup-plugin-babel`.

For some context, we are currently looking at migrating [microbundle](https://github.com/developit/microbundle) to babel, giving the user more flexibility, but implementing a default config by detecting config files has caused some headaches. See the discussion in https://github.com/developit/microbundle/pull/263#pullrequestreview-181930813.

Having a utility like `babel-loaders`'s customized loader would enable tools to, among other things, update the babel config in a safer way, relying on a documented API instead of a flimsy process of looking for a set of files and configuration properties.

I would love to get your thoughts on this. Maybe even some ideas on API and where to start looking for anyone interested in implementing this.

**Comment by Andarist** [comment]
We definitely want this - if you can work on it (replicating babel-loader's functionality) it would be great, we could move this together quite quickly. If not - I'm going to research the topic in few days and implement it myself.

**Comment by esphen** [comment]
Sounds fun. I can have a stab at it tomorrow, see if I make some progress. 

If I need help at some point, I'll open a PR and we can take the discussion there.

**Comment by FezVrasta** [comment]
@esphen I created a PR against your branch to fix some stuff
https://github.com/esphen/rollup-plugin-babel/pull/1

**Comment by Andarist** [comment]
This has been released in 4.3.0
