### ISSUE TITLE
How to locate babel.config.js

### ISSUE THREAD

**Issue by kopax** [rollup/rollup-plugin-babel#279]
We have removed .babelrc in profit of `babel.config.js`, after upgrading from rollup v0.57 to latest, we encounter the following error:

```

> 1659 | export default ColorWrapper;
       |       ^ Unexpected token: keyword (default)
  1660 | export { ColorMock };
[!] (uglify plugin) Error: Unexpected token: keyword (default)
SyntaxError: Unexpected token: keyword (default)

```

We use `babelrc: false`, Is there a way to select the `babel.config.js` file?

**Comment by nicolo-ribaudo** [comment]
Is `configFile: "path/to/babel.config.js"` what you are looking for?

**Comment by kopax** [comment]
Thanks you, it seems that I have passed the configuration to babel plugin, however, I keep having error while trying to build with rollup.

This happen after I have upgraded rollup from 0.57.1 to latest.

**Comment by nicolo-ribaudo** [comment]
What is your directory structure?

**Comment by kopax** [comment]
Thanks, I have found this is not rolated to that module, I have opened another issue [here](https://github.com/rollup/rollup/issues/2597)
