### ISSUE TITLE
Bug when using default exports

### ISSUE THREAD

**Issue by Pauan** [rollup/rollup-plugin-babel#28]
Here is a [reduced test case](https://github.com/rollup/rollup-plugin-babel/files/77859/test.zip).

Please unzip it and then run `npm install`

You will see the output in the file `build.js`

As you can see, the `build.js` file is empty, but it should *not* be empty.

----

* If I remove `rollup-plugin-babel`, then it works (but without transpilation).

* If I use named exports (`import { bar } from "./bar"`) rather than default exports (`import bar from "./bar"`), then it works correctly.

* If I use `function () { ... }` rather than `() => { ... }`, then it works correctly.

**Comment by Rich-Harris** [comment]
Turns out this is a bug in Rollup itself – will close this in favour of https://github.com/rollup/rollup/issues/421. Thanks!
