### ISSUE TITLE
Why++ ?

### ISSUE THREAD

**Issue by deanmartinez** [rollup/rollup-plugin-babel#293]
Hello, I can see the [Why section in the readme](https://github.com/rollup/rollup-plugin-babel#why) which states 
> you're using Babel to transpile your ES6/7 code and Rollup to generate a standalone bundle

My question is **why** would someone be in that condition? Sorry if I am not understanding. As far as I can tell:
* Babel *converts ECMAScript 2015+ code into a backwards compatible version of JavaScript*
* Rollup *uses the new standardized format for code modules included in the ES6 revision of JavaScript*

Seems like these people are already **using the latest version of JavaScript**. They are ready to go with Rollup (which bundles). So I don't see the place where Babel (which transpiles) is necessary? 🤔

I can see that many people are using this library, so clearly I'm missing a key concept.
Sorry if that sounds obtuse. Thanks in advance for helping me understand!

**Comment by Andarist** [comment]
Babel handles more than module format transpilation. While it's true that ESM module format is part of ECMAScript 2015+, it doesn't mean that you want to ship ECMAScript 2015+ code to your users (you might need to support older browsers).

The new module format allows rollup for smarter bundling, which is not tightly coupled to the rest of the code being written using new versions of JavaScript. 

Babel is also just for syntax transformation, rollup actually resolves your files and "concatenates" them into single (or more) output files (which babel doesn't - it operates on single files only).

You might read some more i.e. [here](https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features).

If something stays unclear - let me know, i'll try to explain the situation better.

**Comment by deanmartinez** [comment]
Thank you for the explanation @Andarist, the [link to the Rollup wiki](https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features) cleared things up for me:
> Wait, it just means import and export – not other future JavaScript features?
Yes.

Appreciate your time. Cheers! 👍
