### ISSUE TITLE
Confused about how to externalize babel helpers in certain circumstances

### ISSUE THREAD

**Issue by Aaron-Pool** [rollup/rollup-plugin-babel#299]
I'm attempting to create a library of vue components. I'm using the @vue/preset-app which automatically includes the `transform-runtime` babel plugin. So, I had set `runtimeHelpers` to true to get the build to run. But I would _still_ like to externalize the babel-helpers so they're not bundled with the library. I have a `@babel/runtime` dependency for the library. So I'm allowing the consumer app to handle resolving these dependencies in the most bundle-size efficient manner.

However, right now, babel is transforming runtime imports into a relative path to the closest @babel/runtime package it can find in my library node_modules. For example, `import _taggedTemplateLiteral from '../../../../../../node_modules/@vue/babel-preset-app/node_modules/@babel/runtime/[...]`. How can I get it to just transform this to `import _taggedTemplateLiteral from '@babel/runtime'`?

My rollup config, in case it's helpful:
```js
import path from 'path';
import babel from 'rollup-plugin-babel';
import nodeResolve from 'rollup-plugin-node-resolve';
import alias from 'rollup-plugin-alias';
import vuePlugin from 'rollup-plugin-vue';
import jsonPlugin from 'rollup-plugin-json';

const pkg = require('./package.json');

const version = pkg.version;

const babelConfig = {
  presets: ['@vue/app'],
  externalHelpers: true,
  runtimeHelpers: true,
  exclude: '!(node_modules/@storybook/addons/src/index.js)node_modules/**'
};

const nodeResolveOptions = {
  module: true,
  jsnext: true,
  preferBuiltins: true,
  extensions: ['.js', '.vue']
};

const aliasOptions = {
  resolve: ['.js', '/index.js'],
  '@': path.resolve(__dirname, 'src')
};

export default {
  input: './src/library.js',
  external: id => id.includes('node_modules') || !(path.isAbsolute(id) || id.startsWith('.') || id.startsWith('@/')),
  treeshake: {
    propertyReadSideEffect: false,
    pureExternalModules: true
  },
  preserveModules: true,
    format: 'esm',
    dir: './dist',
    name: [omitted],
    globals: {
      vue: 'Vue'
    },
    sourcemap: true
  },
  plugins: [babel(babelConfig), alias(aliasOptions), nodeResolve(nodeResolveOptions), vuePlugin(), jsonPlugin()]
};
```

**Comment by Andarist** [comment]
This is caused by this https://github.com/vuejs/vue-cli/blob/c078633be1127b0dd19b0ccb1b6cb6022288d960/packages/%40vue/babel-preset-app/index.js#L62

You should be able to override this behaviour with something like `['@vue/babel-preset-app', { absoluteRuntime: false }]`

**Comment by Aaron-Pool** [comment]
Great! I'll give that a try. Appreciate the super timely response.

**Comment by Aaron-Pool** [comment]
Well, wanted to update you to let you know that overriding that option did not fix the issue. But since I can see that this isn't an issue with this plugin, but the vue preset, you're fine to close this.

**Comment by Andarist** [comment]
If you want you can share your current setup (in a manner that I could do `npm install && npm run build` or similar) and I could take a quick look at it.

**Comment by Aaron-Pool** [comment]
Ok, I'll see if I can get a minimal repro for you at some point today.

**Comment by Andarist** [comment]
The repro case has not been provided for quite some time, so I assume the issue is stale and as there are no actionable points here for me - I'm going to close it.
