### ISSUE TITLE
.babelrc of npm dependencies

### ISSUE THREAD

**Issue by troch** [rollup/rollup-plugin-babel#30]
Hi,

I am trying to bundle a library, including npm dependencies with `jsnext:main` configured.

It is failing at the preflight check, complaining about module transformation and demanding the use of "presets-es2015". It seems options from `.babelrc` of my package get overwritten (or extended) by `.babelrc` options of the npm dependency I am trying to include.

The problem is that `filename` is passed to `babelCore.transform()`, causing babel to use local `.babelrc` files (https://github.com/rollup/rollup-plugin-babel/blob/master/src/index.js#L22).

It can be fixed by passing `path.join(process.cwd(), 'x.js')` instead of `path.join(dir, 'x.js')`, in order to force babel to use `.babelrc` from the working dir instead of local ones. But it would be an issue for a code base with nested .babelrc files in its source directory, or with babelrc files not in the root directory / working dir, etc...

__Here is how I came round that issue:__

Using rollup forced me to modify my .babelrc files to use different env, so I could have different settings when using babel for tests, for building individual commonjs modules to be consumed with npm (using babel directly) or using rollup for AMD, UMD and iife bundles. So instead of having to modify my .babelrc, I added babel options to my `rollup.config.js`, and set `babelrc` to false (preventing babel to use them).

```javascript
import babel from 'rollup-plugin-babel';
import uglify from 'rollup-plugin-uglify';
import npm from 'rollup-plugin-npm';
import { argv } from 'yargs';

const babelOptions = {
    presets: [ 'es2015-rollup' ],
    plugins: [
        'transform-object-rest-spread',
        'transform-class-properties',
        'transform-export-extensions'
    ],
    babelrc: false
};

const format = argv.format || 'iife';
const dest = {
    amd:  'dist/amd/router5.js',
    umd:  'dist/umd/router5.js',
    iife: 'dist/browser/router5.js'
}[format];

export default {
    entry: 'modules/index.js',
    format,
    plugins: [ babel(babelOptions), npm({ jsnext: true }) ],
    moduleName: 'router5',
    moduleId: 'router5',
    dest
};
```

PS: I know ideally .babelrc files should be excluded from npm packages

**Comment by Rich-Harris** [comment]
Yeah. This is exactly why I believe library authors shouldn't expose untranspiled source code, but should always transpile – it just introduces way too much surface area for bugs, such as discrepancies between Babel configurations and versions. In my view `jsnext:main` should mean exactly the same thing as `main`, except with `import` and `export` instead of CommonJS or UMD code.

I think the `babelrc: false` is the only sensible approach if you do need to transpile your dependencies (though even that could fail depending on what plugins are used) – long term, the solution is to discourage library authors from distributing untranspiled code.

**Comment by developit** [comment]
@troch You could always manually read in just your project's `.babelrc`:

```js
import babel from 'rollup-plugin-babel';
import uglify from 'rollup-plugin-uglify';
import npm from 'rollup-plugin-npm';
import fs from 'fs';
import { argv } from 'yargs';

const babelOptions = JSON.parse(fs.readFileSync('./babelrc'));

const format = argv.format || 'iife';
const dest = {
    amd:  'dist/amd/router5.js',
    umd:  'dist/umd/router5.js',
    iife: 'dist/browser/router5.js'
}[format];

export default {
    entry: 'modules/index.js',
    format,
    plugins: [
        babel({ ...babelOptions, babelrc: false }),
        npm({ jsnext: true })
    ],
    moduleName: 'router5',
    moduleId: 'router5',
    dest
};
```

**Comment by eventualbuddha** [comment]
Is there anything to do with this one? A note to put in the website? Otherwise we should close.

**Comment by developit** [comment]
I think throwing my answer (if is acceptable) on the wiki would be sufficient, unless you guys wanted to add a `shallowBabelrc` option to `rollup-plugin-babel`.

**Comment by eventualbuddha** [comment]
I've been starting to do essentially what you describe, so I think putting it in the wiki is fine. My only question is whether `...babelOptions` will work inside a `rollup.config.js`. Doesn't everything except module syntax inside there have to be able to run in whatever version of node.js you're using?

**Comment by developit** [comment]
Afaik it gets transpiled. Certainly ESM are supported https://github.com/developit/preact/blob/master/rollup.config.js

**Comment by eventualbuddha** [comment]
Yes, modules, but nothing else is my understanding. Otherwise rollup would have to somehow include babel, right?

**Comment by developit** [comment]
Hmmm. Now you have me wondering...

**Comment by developit** [comment]
Interestingly, greenkeeper [just updated](https://github.com/developit/preact/pull/12) my `rollup-plugin-babel` and I'm [now seeing this issue](https://travis-ci.org/developit/preact/jobs/102796294) when I wasn't before.

**Comment by eventualbuddha** [comment]
Odd. I just released v2.3.9 and the only thing that should have changed was undoing the renaming of the `babelHelpers` stuff.

**Comment by developit** [comment]
Hope it wasn't me dropping the ball on getting [this](https://github.com/developit/modify-babel-preset/issues/1#issuecomment-170385169) fixed quickly..

**Comment by eventualbuddha** [comment]
@developit from rollupjs.org:

> Note that Rollup itself processes the config file, which is why we're able to use export default syntax – the code isn't being transpiled with Babel or anything similar, so you can only use ES2015 features that are supported in the version of Node.js that you're running.

Also, what is that linked issue about? Is there anything I could help with?

**Comment by developit** [comment]
@eventualbuddha The issue @Rich-Harris noticed seemed to be finding Babel plugins via NPM 2, but I have not yet been able to trigger it.  If you are able, it would be incredibly helpful to reproduce that failed build.  It's still `master` of [babel-preset-es2015-rollup](https://github.com/rollup/babel-preset-es2015-rollup), @Rich-Harris released from the `fix` branch that reverts the integration.

**Comment by troch** [comment]
> Is there anything to do with this one? A note to put in the website? Otherwise we should close.

That is why I opened this "issue", just so it can be found by people who experience the following error when using rollup-plugin-npm: `'It looks like your Babel configuration specifies a module transformer. Please disable it. If you\'re using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information`. A note on the website would be great!

**Comment by Rich-Harris** [comment]
> My only question is whether ...babelOptions will work inside a rollup.config.js. Doesn't everything except module syntax inside there have to be able to run in whatever version of node.js you're using?

That's correct – Rollup rolls up the config file, it doesn't run it through Babel. 

> Interestingly, greenkeeper just updated my rollup-plugin-babel and I'm now seeing this issue when I wasn't before.

The `loose` option only applies to Babel 5 – if you're using an up-to-date version of this plugin you'll need a Babel 6 config. 

> Is there anything to do with this one? A note to put in the website? Otherwise we should close

I guess all we can do is discourage people from transpiling their dependencies. I've added a [note](https://github.com/rollup/rollup-plugin-babel/blob/master/README.md#external-dependencies) to that effect in the README, so I'll close this issue.
