### ISSUE TITLE
How to exclude babel helpers from bundle for babel 7

### ISSUE THREAD

**Issue by ravecat** [rollup/rollup-plugin-babel#300]
Try to exclude helpers from bundle according to [docs](https://github.com/rollup/rollup-plugin-babel#helpers) (but with that I use `"@babel/core": "7.2.2"` and `"rollup-plugin-babel": "^4.3.2",`)

```
  babel({
    exclude: "node_modules/**",
    plugins: [
      "@babel/plugin-external-helpers"
    ],
    externalHelpers: true
  }),
```

And get error on build

```
[!] (babel plugin) Error: Runtime helpers are not enabled. Either exclude the transform-runtime Babel plugin or pass the `runtimeHelpers: true` option. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
src/index.js
Error: Runtime helpers are not enabled. Either exclude the transform-runtime Babel plugin or pass the `runtimeHelpers: true` option. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at error (/home/max/project/styled-components-toolbox/node_modules/rollup/dist/rollup.js:3600:30)
    at Object.error (/home/max/project/styled-components-toolbox/node_modules/rollup/dist/rollup.js:16926:17)
    at Object.error (/home/max/project/styled-components-toolbox/node_modules/rollup/dist/rollup.js:17335:31)
    at /home/max/project/styled-components-toolbox/node_modules/rollup-plugin-babel/src/index.js:103:12

error Command failed with exit code 1.

```

With enabled `runtimeHelpers` build is ok

```
  babel({
    exclude: "node_modules/**",
    runtimeHelpers: true
  }),
```
 but bundle has more size.

How to exclude babel helpers from bundle for babel 7?

Code for reproduction available here

1. `git clone https://github.com/ravecat/styled-components-toolbox.git --single-branch --branch issue/rollup-plugin-babel-external-helpers`
2. `yarn`
3. `yarn build`

**Comment by Zousdie** [comment]
If you use babel 7, you need this babel plugin: @babel/plugin-transform-runtime.

babel.config.js:
```javascript
module.exports = {
  presets: [
    '@babel/preset-env',
  ],
  plugins: [
    [
      '@babel/plugin-transform-runtime',
      {
        corejs: false,
        helpers: true,
        regenerator: false,
        useESModules: true,
      },
    ],
  ],
};
```

rollup.config.js:
```javascript
export default {
    input: 'src/main.js',
    output: [
      {
        file: 'esm/index.js',
        format: 'es',
      }
    ],
    plugins: [
      babel({
        exclude: 'node_modules/**',
        runtimeHelpers: true,
      }),
    ],
    external (id) {
      return /@babel\/runtime/.test(id);
    },
  },
```

reference: [https://babeljs.io/docs/en/babel-plugin-transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime)

**Comment by ravecat** [comment]
@Zousdie yep, I know about runtime plugin, but I want exclude babel helpers from my bundle according docs https://github.com/rollup/rollup-plugin-babel#helpers and use external-helpers

**Comment by Andarist** [comment]
The external function receives every id which rollup tries to load, if it returns true then rollup will leave the import in place (it wont bundle it), if it returns false though then it will bundle it (default behaviour).
