### ISSUE TITLE
Vue-cli + Rollup plugin babel: Unexpected Situation arose

### ISSUE THREAD

**Issue by DonNicoJs** [rollup/rollup-plugin-babel#302]
I am building a library with vue-cli ( for the dev part ) and rollup to build the library. 
I updated everything to the latest  version and I started to receive this error

`(babel plugin) Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!`

Simply swapping babel preset in babel.config.js from

```js
module.exports = {
  presets: ["@vue/app"]
};
```

To

```js
module.exports = {
  presets: [
    [
      "@babel/preset-env",
      {
        useBuiltIns: "usage"
      }
    ]
  ],
  plugins: ["@babel/plugin-syntax-dynamic-import"]
};
```

Fixed both the build and the dev ( rollup and vue-cli respectively ) 

Relevant part of package.json (post adding preset-env)

```
    "@babel/core": "^7.3.4",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/preset-env": "^7.3.4",
    "@vue/cli-plugin-babel": "^3.5.0",
    "@vue/cli-plugin-eslint": "^3.5.0",
    "@vue/cli-plugin-unit-jest": "^3.5.0",
    "@vue/cli-service": "^3.5.0",
    "@vue/eslint-config-prettier": "^4.0.1",
    "@vue/test-utils": "^1.0.0-beta.20",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.3.1",
    "eslint": "^5.15.1",
    "eslint-plugin-vue": "^5.2.2",
    "husky": "^1.3.1",
    "lint-staged": "^8.1.5",
    "rollup": "^1.6.0",
    "rollup-copy-plugin": "^0.1.0",
    "rollup-plugin-babel": "4.3.2",
    "rollup-plugin-commonjs": "^9.2.1",
    "rollup-plugin-node-resolve": "^4.0.1",
    "rollup-plugin-replace": "^2.1.0",
    "rollup-plugin-vue": "^4.7.2",
    "vue": "^2.6.8",
    "vue-template-compiler": "^2.6.8",
```

**Comment by nicolo-ribaudo** [comment]
This looks like a bug with the `@vue/app` preset.

**Comment by Andarist** [comment]
Could you share repository with the issue reproduced? Hard to tell what's wrong without being able to test it.

**Comment by DonNicoJs** [comment]
@Andarist yes sure, this evening I should have it online!

**Comment by DonNicoJs** [comment]
@Andarist Okay I tried to revert the fix and now.. is working even with `@vue/app`. What I did in between was switching my node version (broken npm)
Closable I think, sorry for the delay and the fuss!
