### ISSUE TITLE
Supporting babel syntax plugins

### ISSUE THREAD

**Issue by detj** [rollup/rollup-plugin-babel#304]
Babel supports [syntax plugins](https://babeljs.io/docs/en/plugins#syntax-plugins), allowing babel to parse the syntax without transforming the code. But `rollup-plugin-babel` [always transforms](https://github.com/rollup/rollup-plugin-babel/blob/18e4232a450f320f44c651aa8c495f21c74d59ac/src/index.js#L112) by default.

For example, for the following babel config

`babel.config.js`
```js
module.exports = {
  plugins: ["@babel/plugin-syntax-jsx"]
}
```

running `rollup -c` throws `Error: Unexpected token` when babel encounters jsx code. I understand, that transforming code is probably the reason why anyone might be using this plugin, but there could be cases where a transform is not desired. Babel does support using only syntax plugins. That way, the full range of babel's functionality is supported.

What are your thoughts on this ?

**Comment by nicolo-ribaudo** [comment]
If Babel doesn't transform JSX, it will give rollup code containing JSX and rollup can't understand it.

**Comment by detj** [comment]
I see. thanks for the quick answer @nicolo-ribaudo
