### ISSUE TITLE
Option to disable preflightCheck

### ISSUE THREAD

**Issue by skeggse** [rollup/rollup-plugin-babel#309]
In optimizing our rollup builds, I noticed that a substantial portion (~16%) of the babel plugin's execution time occurs in the preflight check. As I best understand it, the preflight check is designed to ensure that the configuration provided to rollup will not conflict with the configuration provided to babel itself, and that this may vary on a file-by-file basis.

For performance reasons, we'd like to be able to disable/override/cache the preflight check's outcome, and I'd like some documentation on what it's intending to accomplish and the cases where it may not be necessary.

**Comment by Andarist** [comment]
It's been implemented in https://github.com/rollup/rollup-plugin-babel/pull/292 but I didn't proceed with that PR further because wasn't sure if the whole thing is a good idea. would appreciate your opinion on changes there.

**Comment by Andarist** [comment]
This is available in v5 alpha releases and will be part of the upcoming v5 release.
