### ISSUE TITLE
Babel plugin not running on ^4.3.0

### ISSUE THREAD

**Issue by deini** [rollup/rollup-plugin-babel#317]
Not sure if I'm missing something but seems like I can't get `babel-plugin-styled-components` to run with `rollup-babel-plugin`.

It seems to work fine using `4.2.0` and below, but anything after `4.3.0` seems to behave differently.

Here is a repo https://github.com/deini/rpb-debug master branch is on `4.3.3` and there is a `4.2.0` branch. There are two directories for `rollup-output` and `babel-output`. You can see the difference in the output from `@babel/cli` vs rollup and how similar they are on the `4.2.0` branch.

**Comment by Andarist** [comment]
I believe this is the same issue as the one investigated here: https://github.com/rollup/rollup-plugin-babel/issues/320#issuecomment-566757103 and it should be reported to styled-components team. Sorry that you had to wait for an answer for so long.
