### ISSUE TITLE
Cannot find rollupPluginBabelHelpers.js

### ISSUE THREAD

**Issue by samrith-s** [rollup/rollup-plugin-babel#318]
I'm using Rollup and Typescript to bundle my library. I'm using this plugin to allow custom `.babelrc`. The thing is, whenever I run build, it gives me this error:
![image](https://user-images.githubusercontent.com/9032162/62115986-ad6ff400-b2b9-11e9-8649-7b98702381ef.png)

Is there any way to fix this? I really need this to convert TS interfaces to PropsTypes! 😞 

Here is the repository: https://github.com/samrith-s/enkel

**Comment by vixeven** [comment]
@samrith-s any updates?

**Comment by tvvignesh** [comment]
@samrith-s Have the same issue. Struggling with this for a long time now. Any idea on how to solve this? Thanks.

**Comment by samrith-s** [comment]
No updates at all. I've stopped development on that, currently, and soon will be switching back to JavaScript for that library.

**Comment by Andarist** [comment]
A fix for this is rather simple - put TS plugin **before** babel plugin in your plugins array. Sorry that you had to wait for an answer for so long.
