### ISSUE TITLE
It takes longer to use the latest version

### ISSUE THREAD

**Issue by chaoranwill** [rollup/rollup-plugin-babel#321]
When I upgraded from version 4.0.1 to latest, it took significantly longer time to build

**Comment by chaoranwill** [comment]
I tested each version again and when I upgraded from version 4.0.3 to version 4.1.0-0, the time spent increasing. And I noticed that you added support for prettier in this version. Is this caused by this reason? Will it be optimized?

**Comment by Andarist** [comment]
Prettier is only a development thing - it doesn't affect build times. The one thing that has changed between those versions is this commit - https://github.com/rollup/rollup-plugin-babel/commit/22f1b81f39ee21cdcbb44147e15bef973615738d - and this, in theory, might lead to longer build times. I haven't noticed it to be a problem though, what are the times (in your case) we are talking about?

**Comment by chaoranwill** [comment]
Oh, Yes, you are right. It not caused by prettier.  I found that it is caused by the commit "Fix preflightChecks for ignored files".

**Comment by chaoranwill** [comment]
@Andarist . Thank you very much for your reply. When I use the previous version, it takes 37 seconds to generate the product using rollup, but now it takes 45 seconds. Since there is a significant increase in time-consuming, are there other optimization options, such as using the original method for some directories, such as node_modules.

**Comment by Andarist** [comment]
Merging this https://github.com/rollup/rollup-plugin-babel/pull/292 would allow you to use `skipBabelHelpersCheck` (or similar). I don't have much time to finish this PR though

**Comment by chaoranwill** [comment]
@Andarist  I found another problem. The judgment condition of the following code seems to be not rigorous, because the return value in _classCallCheck is also included, resulting in unnecessary repeated execution of the transform function. Is this a mistake or I am wrong?

`if (~check.indexOf('class ')) {
	check = transformSync(inputCode, addBabelPlugin(options, fallbackClassTransform)).code;
 }`
 
`function _classCallCheck(instance, Constructor) {
        if (!(instance instanceof Constructor)) 
             { throw new TypeError(\"Cannot call a class as a function\"); } 
 }`

**Comment by Andarist** [comment]
Do you mean that the check fails because of the resulting output containing that error string which has "class " in it?

**Comment by chaoranwill** [comment]
Sorry, I got it wrong, please ignore the above question. But I still don't know what kind of problem you are trying to solve by changing preflightChecks.  If I continue to use the previous version, what kind of scenario will there be a problem? Thanks again 🙏

**Comment by Andarist** [comment]
Not sure what do you mean, preflightChecks are supposed to catch developers misconfiguring this plugin. I don't want to change them, just want to provide a way to disable them entirely for power users who don't want to waste time on them and who are sure they know how to configure things without this plugin verifying it.

**Comment by chaoranwill** [comment]
I found the answer here #16  . I understand that this is done to avoid ignoring the local .babelrc file. If I set babelrc: false and customize the configuration file, the change of preflightCheck have no effect on my project. Am I correct?

**Comment by Andarist** [comment]
Still not sure if we are on the same page. At the moment (with current v4) `preflightCheck` is just something that happens within this plugin and is not something you can disable or configure in any way. 

The preflightCheck gives us information about how your babel is configured for a certain file and that information is used to determine if rollup-plugin-babel has been configured correctly with externalHelpers/runtimeHelpers/inlineHelpers options.

**Comment by Andarist** [comment]
With `5.0.0-alpha.1` (soon to be released as a stable version - just need to migrate this plugin to Rollup plugins monorepo and update docs) you can disable those preflight checks by passing `skipPreflightCheck: false` to the plugin.

I believe this addresses your issue so I think this can be closed now. If you still have any other issues - please just open a new one.
