### ISSUE TITLE
babel.generated is not function

### ISSUE THREAD

**Issue by Joyzen** [rollup/rollup-plugin-babel#341]
How long do you publish the latest version?

**Comment by Andarist** [comment]
You can use `5.0.0-alpha.1` which has this feature in it. Final v5 will be released within 2 weeks (or so) under `@rollup` scope - we are at the moment migrating this plugin into plugins monorepo ( https://github.com/rollup/plugins )

**Comment by Joyzen** [comment]
got it,so the documention happen to be ahead of the current npm package version...

thank for your reply and works.

**Comment by Andarist** [comment]
Yes - docs were ahead of the latest release. I’ve removed those parts now to avoid confusion for others as well
