### ISSUE TITLE
Problem with ESM import syntax with pluginutils

### ISSUE THREAD

**Issue by brettz9** [rollup/rollup-plugin-babel#348]
Hi,

Thanks for the very handy plugin.

As per https://github.com/rollup/plugins/issues/171 , it seems that as long as pluginutils is exporting a default (only), your ESM syntax at https://github.com/rollup/rollup-plugin-babel/blob/ae788a383be8e70d1efda51f7a42277fffd79f9a/src/index.js#L2 should by importing it with a syntax like this instead:

```js
import pluginutils from 'rollup-pluginutils';

const {createFilter} = pluginutils;
```

And actually, with the old version of pluginutils deprecated, it really should be pointing to `@rollup/pluginutils` instead:

```js
import pluginutils from '@rollup/pluginutils';

const {createFilter} = pluginutils;
```

**Comment by brettz9** [comment]
Btw, while it may work with some compilers or configurations, the above is required for those which adhere strictly to ESM.

**Comment by Andarist** [comment]
There is an ongoing effort to migrate this plugin to the plugins monorepo - https://github.com/rollup/plugins/pull/108 . I'm afraid we won't be fixing this for v4, but I will make sure that it's fixed for the upcoming v5 (which is going to be released when this mentioned PR lands). Hope you understand.
