### ISSUE TITLE
ES6 gulpfile.babel.js preset conflict with rollup

### ISSUE THREAD

**Issue by rosskevin** [rollup/rollup-plugin-babel#35]
Since `.babelrc` is global, and I want to use an ES6 gulpfile, I was expecting to be able to pass a preset into rollup that was discrete from this. 

```javascript
import gulp from 'gulp'
import rollup from 'gulp-rollup'
import sourcemaps from 'gulp-sourcemaps'
import babel from 'rollup-plugin-babel'

gulp.task('rollup:es6', () => {
  gulp.src('lib/index.js', {read: false})
    .pipe(rollup({
      sourceMap: true,
      plugins: [babel({
        "presets": ["es2015-rollup"]
      })],
      format: 'es6',
      dest: 'dist/gulp-pipeline.es6.js'
    }))
    .pipe(sourcemaps.write(".")) 
    .pipe(gulp.dest('dist'))
})
```

With .babelrc `{ "presets": [ "es2015" ] }` I get the typical: 

```
Error: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
```

If I do as recommended and set .babelrc `{ "presets": [ "es2015-rollup" ] }`, then the babel that gulp is using to transpile gulpfile.babel.js fails:

```
$ gulp rollup:es6
[18:07:51] Requiring external module babel-core/register
/Users/kross/projects/gulp-pipeline/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^

SyntaxError: Unexpected token import
```

Any recommendations on using an ES6 gulpfile with preset es2015 and running rollup from it with preset es2015-rollup?

**Comment by rosskevin** [comment]
I'm reviewing this one now, potential duplicate:
https://github.com/rollup/babel-preset-es2015-rollup/issues/2

**Comment by rosskevin** [comment]
Ok, the solution with putting the .babelrc file in the lower folder works.

I have switched to the gulp rollup-stream, but I would like to voice my opinion that we should be able to do this with discrete settings passed to rollup, instead of this extra .babelrc file.

Here is what works with the extra .babelrc in the lib folder:
```
gulp.task('rollup:es6', () => {
  return rollup({
    entry: './lib/index.js',
    sourceMap: true,
    plugins: [
      babel()
    ]
  })
  // point to the entry file.
  // if you want to output with a different name, rename it at the end using gulp-rename.
    .pipe(source('index.js', './lib'))
    // buffer the output. most gulp plugins, including gulp-sourcemaps, don't support streams.
    .pipe(buffer())
    // tell gulp-sourcemaps to load the inline sourcemap produced by rollup-stream.
    .pipe(sourcemaps.init({loadMaps: true}))
    // transform the code further here.
    // write the sourcemap alongside the output file.
    .pipe(sourcemaps.write('.'))
    // and output to ./dist/main.js as normal.
    .pipe(rename("gulp-pipeline.es6.js"))
    .pipe(gulp.dest('./dist'));
});
```

I would prefer this top section to be:

```
gulp.task('rollup:es6', () => {
  return rollup({
    entry: './lib/index.js',
    sourceMap: true,
    plugins: [
      babel({presets: ["es2015-rollup"]})
    ]
  })
...
```

Feel free to close this as I have a working solution, I just wanted to voice an opinion for discrete settings passed to rollup.

**Comment by TrySound** [comment]
@rosskevin You don't need any stream/buffer adapters. You can use rollup directly and return promise in gulp task. Just like this
https://github.com/TrySound/case/blob/3.0/gulpfile.js#L33-L53

**Comment by eventualbuddha** [comment]
You can also specify `babelrc: false` to make Babel not use the config from the file. Closing as there doesn't seem to be anything to do here except maybe documentation.

**Comment by rosskevin** [comment]
@TrySound thanks for the pointer.

**Comment by josdejong** [comment]
@eventualbuddha thanks for the tip, this helped me get Rollup+ES2015 working in combination with AVA+ES2015, which also results in conflicting babel presets.

**Comment by tomwayson** [comment]
@josdejong

Would you mind sharing your config for rollup and ava? I'm trying to do the same, [but I can't get it to work](https://github.com/tomwayson/esri-rollup-example/issues/16#issuecomment-213848576).

Thanks!

**Comment by josdejong** [comment]
Yes, it was for [this project](https://github.com/josdejong/lossless-json/).

The "trick" is to configure `babelrc: false` in the configuration of the babel plugin in the `rollup.config.js` file.

The `package.json` looks like:

```
{
  "scripts": {
    "test": "ava test-*.test.js test/**/*.test.js",
    "build": "rollup --config rollup.config.js"
    ...
  },
  "devDependencies": {
    "ava": "^0.11.0",
    "babel-cli": "^6.5.1",
    "babel-preset-es2015-rollup": "^1.1.1",
    "rollup": "^0.25.3",
    "rollup-plugin-babel": "^2.3.9",
    "rollup-plugin-uglify": "^0.2.0",
    "uglify-js": "^2.6.1"
  },
  ...
}
```

The file `.babelrc` contains:

```
{
  "presets": ["es2015"]
}
```

And `rollup.config.js` contains:

```
import babel from 'rollup-plugin-babel';
import uglify from 'rollup-plugin-uglify';

export default {
  entry: 'lib/index.js',
  dest: 'dist/lossless-json.js',
  format: 'umd',
  moduleName: 'LosslessJSON',
  sourceMap: true,
  plugins: [
    babel({
      babelrc: false,
      presets: ["es2015-rollup"]
    }),
    uglify()
  ]
};
```

**Comment by tomwayson** [comment]
Thanks @josdejong!

I was under the impression from previous comments that Rollup *had* to use .babelrc, so I was trying to get AVA to use another babel configuration. So I was able to [configure Rollup to ignore .babelrc and specify the babel config in my gulp task](https://github.com/tomwayson/esri-rollup-example/blob/b24ccaaf9213dba2d6122c584260b3a292b39996/gulpfile.js#L35-L41) the same way you specified it in your rollup config above. Thanks for that!

However, it still looks like AVA is not compiling node_modules for me, so it's not quite working yet, but things are good on the Rollup side.

**Comment by josdejong** [comment]
Good to hear :)
