### ISSUE TITLE
sourcemaps incorrect

### ISSUE THREAD

**Issue by GerardRodes** [rollup/rollup-plugin-babel#351]
The sourcemaps of my final bundle contain transpiled code, when shouldn't

The scenario is the following
`App` => `dependency`

Both packages with following configuration
```
// rollup.config.js
output: {
    format: 'esm',
    dir: 'dist',
    sourcemap: true,
  },
 plugins: [ babel() ]
```
and
```
// .babelrc
{
    "sourceMaps": true,
    "inputSourceMap": true,
}
```

And then when inspecting `App` source code on the browser, transpiled code from `dependency` is shown
```js
function hex(c) {
  var _Vue$$oa2, _Vue$$oa2$theme;

  let color = (Vue$1 === null || Vue$1 === void 0 ? void 0 : (_Vue$$oa2 = Vue$1.$oa) === null || _Vue$$oa2 === void 0 ? void 0 : (_Vue$$oa2$theme = _Vue$$oa2.theme) === null || _Vue$$oa2$theme === void 0 ? void 0 : _Vue$$oa2$theme[c]) || c;

  if (typeof c !== 'string') {
    return Rgb2Hex(rgb(c));
  }

  return normalizeHex(color);
}
```

**Comment by Andarist** [comment]
The issue lacks sufficient information. Please create a runnable repro case so we could check your setup more easily. When you do so - please open a new issue in this repository: https://github.com/rollup/plugins , as this plugin has been migrated over there.
