### ISSUE TITLE
Support rollup v2

### ISSUE THREAD

**Issue by limonte** [rollup/rollup-plugin-babel#353]
v2 has been released: https://github.com/rollup/rollup/releases/tag/v2.0.0 and with v2 this warning is shown:

```
warning " > rollup-plugin-babel@4.3.3" has incorrect peer dependency "rollup@>=0.60.0 <2".
```

**Comment by Andarist** [comment]
I've just published 4.4.0 which allows for Rollup 2 in the peer dependency range.
