### ISSUE TITLE
Failed to locate module "rollup" from "."

### ISSUE THREAD

**Issue by AzadKshitij** [rollup/rollup-plugin-babel#354]
I am not able to pack my electron app

#package.json
{
  "name": "visual_code",
  "version": "1.0.0",
  "description": "This is a good text editor for html and other languages also",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build": "rollup -c",
    "package": "electron-packager . dist --platform=win32 --arch=x64 --app-version=1.0.0"
  },
  "keywords": [
    "visual_code"
  ],
  "author": "Azad Kshitij",
  "license": "ISC",
  "devDependencies": {
    "electron": "^8.0.1",
    "rollup": "^2.0.2"
  }
}

#rollup.config.js

export default {
  input: "main.js",
  output: {
    file: "./build/main.min.js",
    format: "iife",
    name: "bundle"
  },
  external: ["electron"]
};

#error
> visual_code@1.0.0 package D:\JavaScript\Electron_App
> electron-packager . dist --platform=win32 --arch=x64 --app-version=1.0.0

Packaging app for platform win32 x64 using electron v8.0.1
Failed to locate module "rollup" from "."

        This normally means that either you have deleted this package already somehow (check your ignore settings if using electron-packager).  Or your module installation failed.

**Comment by Andarist** [comment]
The issue lacks sufficient information. Please create a runnable repro case so we could check your setup more easily. When you do so - please open a new issue in this repository: https://github.com/rollup/plugins , as this plugin has been migrated over there.
