### ISSUE TITLE
Make this output plugin

### ISSUE THREAD

**Issue by dilyanpalauzov** [rollup/rollup-plugin-babel#360]
In Rollup a single entry can contain several outputs and each otput can have its own output plugins.

Please make possible to use rollup-plugin-babel as output plugin, so that a single rollup configuration can create both module and nomodule version (after passing different options/preset to the rollup-plugin-babel() in rollup.config.js)

**Comment by huzedong2015** [comment]
@Andarist
I have the same problem
rollup-plugin-babel@next or @latest

**Comment by Andarist** [comment]
It's possible to use this as output plugin with when using `next` version. I hope to get it released as stable `@rollup/plugin-babel` soon - see the migration PR here: https://github.com/rollup/plugins/pull/108

**Comment by Andarist** [comment]
The migration is complete and the version supporting this has been released as `@rollup/plugin-babel@^5`
