### ISSUE TITLE
Does include exclude everything not listed in the array/pattern?

### ISSUE THREAD

**Issue by CrashyBang** [rollup/rollup-plugin-babel#364]
I was looking at #323 and want to do something similar, my current solution is:

```
babel({
    extensions: ['.js', '.mjs', '.html', '.svelte'],
    include: ['src/**', 'node_modules/svelte/**']
})
```

My question is does this explicitly exclude all other `node_modules`?

**Comment by Andarist** [comment]
> My question is does this explicitly exclude all other node_modules?

Yes, if you specify `include` pattern then by nature only those files are included which means that everything else is excluded.
