### ISSUE TITLE
Cannot specify option 'extensions'

### ISSUE THREAD

**Issue by Misaka-0x447f** [rollup/rollup-plugin-babel#365]
![image](https://user-images.githubusercontent.com/15797507/81279014-1a09f180-9089-11ea-94ea-6165bfc6edf7.png)
Heres what I got. I did a console log for config the plugin got.

**Comment by loganfsmyth** [comment]
`extensions` is an option to `rollup-plugin-babel`, not an option to Babel itself, so you need to pass it directly to the plugin from via your Rollup configuration file.

**Comment by Misaka-0x447f** [comment]
> `extensions` is an option to `rollup-plugin-babel`, not an option to Babel itself, so you need to pass it directly to the plugin from via your Rollup configuration file.

Wait... You can only merge plugin options and babel options in this plugin...

**Comment by Andarist** [comment]
It looks like you have tried to pass `extensions` via Babel config file but you should pass it to `rollup-plugin-babel` itself
