### ISSUE TITLE
Invoking the plugin multiple times breaks babel helpers

### ISSUE THREAD

**Issue by mark-rushakoff** [rollup/rollup-plugin-babel#38]
Hi rollup team,

I was playing around with rollup this weekend and you all are building a really cool tool. I like how conceptually simple it is, and I'm quite happy with the bundle output. I've added a lot of detail in this issue in an attempt to demonstrate the struggles I've experienced getting started. I'm not sure if multiple invocations of the plugin is a bug or a misuse/misunderstanding of the tool, but hopefully my explanation can help  paint a picture of a new user's experience, at least.

I'm importing a project with jsnext:main but with ES6 code present (default argument assignment, arrow functions, etc.). It took me **hours** of reading through documentation and issues to understand that rollup considers this an issue with the module being imported. I expected that I would be able to import it without any trouble, just because it specified jsnext:main. (The library is [reselect](https://github.com/rackt/reselect); I'd be happy to open an issue for them to stop distributing [this file](https://github.com/rackt/reselect/blob/f73c1f224be6ce8e6bd8a096466a317a02ca5954/src/index.js) without transpiling it first, but I'm really unsure of what language to use, or what further documentation I can link to, to explain why they're doing it wrong.)

First I configured my babel plugin as

```js
babel({
  exclude: 'node_modules/**',
}),
```

and reselect didn't get transpiled, so I got syntax errors when I tried to load the code in Chrome.

I eventually figured out that I needed to transpile reselect, so I changed my babel plugin config to

```js
babel({
  include: [
    'src/**/*.js',
    'src/*.js',
    'test/**/*.js',
    'test/*.js',
    'node_modules/reselect/**/*.js',
  ],
}),
```

It worked, but it was ugly. So then I had the bright idea of invoking the plugin twice, so I could fully exclude node_modules in one plugin and whitelist the folders within node_modules in the other:

```js
babel({
  exclude: 'node_modules/**'
}),
babel({
  include: [
    'node_modules/reselect/**/*.js',
  ],
}),
```

And this would have worked... but here was the code at the top of my bundle, with a couple annotative comments added by me for further context:

```js
(function (exports) {
    'use strict';

     // *My* code used defineProperty...
    var babelHelpers = {};

    babelHelpers.defineProperty = function (obj, key, value) {
      if (key in obj) {
        Object.defineProperty(obj, key, {
          value: value,
          enumerable: true,
          configurable: true,
          writable: true
        });
      } else {
        obj[key] = value;
      }

      return obj;
    };

    babelHelpers;


    // reselect's code used typeof undefined and something with rest args, I think.
    // This second occurrence of `var babelHelpers = {};` wipes out the previous occurrence, 
    // so when the bundle gets to my code, babelHelpers.defineProperty is undefined.
    var babelHelpers = {};
    babelHelpers.typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
      return typeof obj;
    } : function (obj) {
      return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj;
    };

    babelHelpers.toConsumableArray = function (arr) {
      if (Array.isArray(arr)) {
        for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) arr2[i] = arr[i];

        return arr2;
      } else {
        return Array.from(arr);
      }
    };

    babelHelpers;

    // And on to the normal stuff...
    var __commonjs_global = typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : this;
```

I'm not sure if the plugin order would have made a difference in this case, but my plugins are ordered multiEntry, replace, npm, babel, babel again, and commonjs.

I hoped to open a PR, but glancing at the code in rollup-plugin-babel, I don't know enough about generating code with Babel to make the change without investing further hours into learning first.

**Comment by thisconnect** [comment]
It took me some time as well. I was missing this see https://github.com/jsforum/jsforum/issues/5

Although with that approach I get babelhelper, babelhelper$1, babelhelper$2

**Comment by Victorystick** [comment]
The plugin is indeed not designed to be used twice in the same Rollup invocation. I understand that the longer configuration is rather ugly, but it's the recommended way to do it. We recommend that people exporting an `jsnext:main` entry point use ES6 module syntax while sticking to ES5 code (or already transpiled ES6) for maximum compatibility.

**Comment by mark-rushakoff** [comment]
@thisconnect I suspect you're not running the latest version, as it looks like recent-ish PRs #34 and #31 affected that behavior.

@Victorystick, two questions.

1. Is there a single, short document somewhere that we can use as a reference for *why* jsnext:main must be ES6 module syntax but otherwise ES5? *I* understand why it makes sense in the context of Rollup, but I feel like all the discussions I've seen on the topic are full of contention and disagreement (especially jsforum/jsforum#5 as @thisconnect linked to). I don't feel like I can easily go to another project and say, "Hey, you should change how you're exporting your ES6 code" because of how loud the dissenting voices are.

2. Should rollup-plugin-babel be able to detect if it's been included multiple times and emit a warning? As it stands now, I think other people can easily fall into the same situation I did, where the build appeared successful, but the code failed at runtime due to a variable getting clobbered by another variable with the same name.

**Comment by eventualbuddha** [comment]
As there's nothing really actionable here, I'm closing this issue. Feel free to continue discussing.
