### ISSUE TITLE
for us new people, how would we use this on a new project?

### ISSUE THREAD

**Issue by paul42** [rollup/rollup-plugin-babel#39]
are there any examples? I'd like to use rollup with react, and I'm trying to learn the right way to use rollup - would I put this into a rollup.config.js and use rollup from the command line? I don't quite follow how to use this, are there any examples? I haven't been able to find any

Thanks in advance,

**Comment by TrySound** [comment]
Here's usage
https://github.com/rollup/rollup-plugin-babel#usage

Just add necessary presets (`babel-preset-es2015-rollup` and `babel-preset-react`) and run `rollup -c`.
To resolve node paths use https://github.com/rollup/rollup-plugin-node-resolve
To process commonjs (not es2015 modules) add https://github.com/rollup/rollup-plugin-commonjs

More information here https://github.com/rollup/rollup/wiki

**Comment by ashnur** [comment]
Guess there is no way to use it from CLI?

**Comment by TrySound** [comment]
@ashnur Why no way? I didn't said that. Rollup does not work out of the box with black jack and jelly. Need some configuration

```js
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: 'src/index.js',
  plugins: [
    nodeResolve({ jsnext: true }),
    commonjs(),
    babel({
      presets: ['es2015-rollup', 'react'],
      exclude: ['node_modules/**']
    })
  ],
  format: 'iife',
  dest: 'dist/index.js'
};
```
Everything is described in babel, rollup and plugins documentations.

**Comment by ashnur** [comment]
That's not cli. I am used to do everything from cli with browserify. I understand that rollup has a different scope that doesn't fit this. 
Honestly, I wouldn't have any idea what to do with the code you gave me. It looks like gulp or grunt or something terrible I avoid at all costs :). It's just way too much wiring. I don't have enough time to learn all this wiring. I am convinced it's needless abstractions mostly.

**Comment by TrySound** [comment]
@ashnur It's config for rollup cli. More information you can always find here
https://github.com/rollup/rollup/wiki/Command-Line-Interface

**Comment by ashnur** [comment]
https://s-media-cache-ak0.pinimg.com/564x/07/09/17/07091781c9e067fcc9281683f1afbcb1.jpg

**Comment by TrySound** [comment]
@ashnur Do you run grunt or gulp cli and something magically happen? Of couse not. CLI is not always everything in command line. You can always use rollup for simple local modules. But for something more compex you should config which prevent lange and ugly commands.

**Comment by ashnur** [comment]
The point of CLI is that I use the command line interface. Not that I use the CLI and something else too. It's as if when you ask for a shiping by airplane and you get shipping by airplain and on surface too. 
If you are wondering what is cli better than configs, it's simple. Config files you have to copy, maintain, manage, track. CLI you just write it once and until the API has some breaking change, you forget. 

You are of course right that rollup isn't the only one tool almost completely giving up on cli (babel is also trying to enforce everyone to use .babelrc, even though it's a ridiculous idea). 
But being one of many doesn't mean that you are right. It only means that if you are making a mistake, you can find someone else to share your grieving with.

**Comment by Victorystick** [comment]
@paul42 Have you taken a look at [the Rollup guide](http://rollupjs.org/guide/)? It's a work in progress, but contains an introduction to using the CLI along with config files.
