### ISSUE TITLE
.jsx files

### ISSUE THREAD

**Issue by vp2177** [rollup/rollup-plugin-babel#44]
Maybe I'm missing something, but surely I should be able to have a module which says

    import FooComponent from './FooComponent'

and have it find `FooComponent.jsx`. By default.

**Comment by TrySound** [comment]
@vp2177 Did you try this https://github.com/rollup/rollup-plugin-node-resolve with `extensions` option ?

**Comment by vp2177** [comment]
Not sure what that is, but the README says 

    for using third party modules in node_modules

**Comment by TrySound** [comment]
@vp2177 It also process local modules like './FooComponent' -> './FooComponent/index.js' or different extension. Use it.

**Comment by vp2177** [comment]
That doesn't make sense. 
Again, from comment #1:
> and have it find FooComponent.jsx. By default.`

**Comment by TrySound** [comment]
@vp2177 It shouldn't look for `.jsx`. `.jsx` is just some custom extension. By default rollup looks for `.js`

**Comment by vp2177** [comment]
@TrySound That's why this issue is filed for `rollup-plugin-babel`, not `rollup`!

**Comment by TrySound** [comment]
rollup-plugin-babel only transpile code. Also there are no any rules/conventions that babel files should have jsx extension.

**Comment by vp2177** [comment]
http://babeljs.io/docs/usage/require/ Just an example, search for `.jsx` there.

Can someone else comment on this issue please?

**Comment by TrySound** [comment]
@vp2177 Okay. You are right. Didn't know. But still this plugin do not resolve paths, only transpiles. Use one of custom resolvers like [node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) or [includepaths](https://github.com/dot-build/rollup-plugin-includepaths)
