### ISSUE TITLE
How I can configure rollup when use it with babel-cli

### ISSUE THREAD

**Issue by max-mykhailenko** [rollup/rollup-plugin-babel#45]
Command in `package.json`
```json
"watch": "BABEL_ENV=es babel example/**/*.js --watch --out-file example/example.min.js",
```

Configuration `.babelrc`
```json
{
  "env": {
    "development": {
      "presets": [ "es2015", "stage-1", "react" ]
    },
    "es": {
      "presets": [ "es2015-rollup", "stage-1", "react" ]
    }
  }
}
```

How I can tell rollup which format it should use `amd`, `umd` etc?

Main goal — dynamic compiling browser ready file, which includes all dependencies: react and my modules. Can I do this in another way?

**Comment by TrySound** [comment]
@max-mykhailenko Why you use babel-cli with rollup?

**Comment by max-mykhailenko** [comment]
> Main goal — dynamic compiling browser ready file, which includes all dependencies: react and my modules.

Want to create workflow when I edit some `jsx` file with dependencies and babel watch got it and compile it to another file which I can insert in browser script tag.

**Comment by TrySound** [comment]
@max-mykhailenko Use different watcher, not babel "out of the box". Babel works fine via this plugin.

**Comment by max-mykhailenko** [comment]
Babel already has watcher and this preset as plugin. Is it really hard to pass configuration file as option? Is it Babel api restrictions?

**Comment by TrySound** [comment]
@max-mykhailenko babel (this module) is plugin of rollup. You can't use rollup from babel-cli. rollup preset is the same stuff except module transpiller because rollup is module handler.

**Comment by Rich-Harris** [comment]
Ultimately the long-awaited `rollup --watch` feature will be the solution to this problem: https://github.com/rollup/rollup/issues/284

**Comment by max-mykhailenko** [comment]
Thanks all!
