### ISSUE TITLE
How do I set up babel's helpers?

### ISSUE THREAD

**Issue by philer** [rollup/rollup-plugin-babel#46]
I'm confused. I want to use babel to enable es6 features like `class` and `await`. I understand that babel requires some helpers to do that and there are multiple ways to access those.  I tried all kinds of configurations but in the end there's always some kind of `regeneratorRuntime` missing which I'm guessing is one of these helpers. The README here isn't particularly detailed on the subject:

> By default, those helpers will be inserted at the top of the file being transformed, which can lead to duplication. It's therefore recommended that you use the external-helpers plugin, which is automatically included in the es2015-rollup preset. Rollup will combine the helpers in a single block at the top of your bundle.

So… what do I do? I can't find a plugin called `external-helpers`. Is this a plugin for babel or for rollup? Do I need some kind of prefix? Do I have to `include` something inside my source files?

I found [babel-plugin-external-helpers](https://www.npmjs.com/package/babel-plugin-external-helpers) and [babel-plugin-external-helpers-2](https://www.npmjs.com/package/babel-plugin-external-helpers-2), but neither of them seem to be doing anything. Which makes sense according to this [blog post](http://www.2ality.com/2015/12/babel6-helpersstandard-library.html) which says I'd have to compile the helpers into a separate file. But that's not what the readme here says (see above).

Here are my dependencies:
```JSON
  "devDependencies": {
    "babel-preset-es2015-rollup": "~1.1.1",
    "babel-preset-stage-2": "^6.5.0",
    "rollup": "~0.25.4",
    "rollup-plugin-babel": "~2.4.0",
    "rollup-plugin-json": "~2.0.0",
    "rollup-plugin-uglify": "~0.3.1"
  },
```
and my rollup.config.js
```JS
import babel from 'rollup-plugin-babel';
import uglify from 'rollup-plugin-uglify';
import json from 'rollup-plugin-json';

var babelOptions = {
  presets: ["es2015-rollup", "stage-2"],
  exclude: 'node_modules/**',
};

export default {
  moduleName: 'thing',
  entry:      'js/index.js',
  dest:       'dist/thing.js',
  sourceMap:  true,
  format:     'iife',
  plugins:    [
    json(),
    babel(babelOptions),
  ],
  external: ['jQuery', 'window', 'document', 'body', 'console'],
};
```
I tried `find node_modules -name "*external-helpers*"` and got
```
node_modules/babel-preset-es2015-rollup/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator/node_modules/babel-core/lib/tools/build-external-helpers.js
node_modules/babel-preset-es2015-rollup/node_modules/babel-plugin-external-helpers
node_modules/rollup-plugin-babel/node_modules/babel-core/lib/tools/build-external-helpers.js
```
Any help would be highly appreciated.

**Comment by mmckenziedev** [comment]
I had the same problem. You need to install more babel plugins. My full config looks like this:

```sh
npm i -D rollup-plugin-babel
npm i -D babel-preset-es2015-rollup
npm i -D babel-plugin-transform-runtime
npm i -D babel-polyfill
```
My plugins array in `rollup.config.js`:

```javascript
plugins: [
	babel({ externalHelpers: false, runtimeHelpers: true };)
]
```

and in my `.babelrc` file:
```json
{
  "presets": [ "es2015-rollup" ],
  "plugins": ["transform-runtime"]
}
```

When it's all done I have these import statements at the top of my file:

```javascript
import _regeneratorRuntime from 'babel-runtime/regenerator';
import _Promise from 'babel-runtime/core-js/promise';
import _classCallCheck from 'babel-runtime/helpers/classCallCheck';
import _createClass from 'babel-runtime/helpers/createClass';
```

**Comment by eventualbuddha** [comment]
This appears to be fixed by @mmckenziedev's comment, so I'm closing. If that doesn't actually resolve the issue, please let us know.

**Comment by piotr-cz** [comment]
I'm having same problem.
During the build process, rollup says
```
Treating 'babel-runtime/helpers/slicedToArray' as external dependency
```
but it's actually not including these so when loading the application I'm getting errors 

```
app.js:2762 Uncaught ReferenceError: _slicedToArray is not defined
```

**Comment by telaviv** [comment]
@piotr-cz Should we make a new issue instead of piggybacking on a closed one?

**Comment by piotr-cz** [comment]
@telaviv
I switched to Bublé in meantime

**Comment by kashifimran** [comment]
I also switched to Bublé. The switch hardly took any time.

**Comment by rxaviers** [comment]
The way I solved this is by having the built package to actually depend on external `regenerator-runtime` and to use `output.intro` to import it.

```js
module.exports = {
  input: "main.js",
  output: {
    file: "dist.js",
    format: "cjs",
    intro: "var regeneratorRuntime = require('regenerator-runtime');\n"
  },
  ...
});
```
