### ISSUE TITLE
Symbol not a Function rolling up babel-runtime@6 / core-js@2

### ISSUE THREAD

**Issue by leeyeh** [rollup/rollup-plugin-babel#51]
Currently `babel-plugin-transform-runtime` depends on `babel-runtime@5`, which works fine with rollup. 
```
├─┬ babel-plugin-transform-runtime@6.7.5
│ └─┬ babel-runtime@5.8.38
│   └── core-js@1.2.6
```

However when `babel-runtime` is upgraded to v6, which depends on `core-js@2`, the bundled file throws an runtime error. Such upgrade may happen when my package or some other dependencies depend on  `babel-runtime@6`。

```
// in this case, babel-runtime@6 may be bundled
─┬ babel-plugin-transform-decorators-legacy@1.3.4
│ ├─┬ babel-runtime@6.6.1
│   └── core-js@2.3.0
├─┬ babel-plugin-transform-runtime@6.7.5
│ └─┬ babel-runtime@5.8.38
│   └── core-js@1.2.6
```

The error shows `Symbol` imported from `babel-runtime@6` is not a Function. I traced `Symbol` but stopped at https://github.com/zloirock/core-js/blob/v2.3.0/library/modules/_core.js in which `Symbol` should be exported. I'm not familiar with `core-js` but I guess some mutations was made during runtime.

The trace log: `babel-runtime/core-js/symbol -> core-js/library/fn/symbol -> core-js/library/modules/_core.js`

Then I required `babel-runtime/core-js/symbol` directly and `core-js/client/library`, both exported `Symbol` as Function as expected. 

Considering `core-js/client/library` was bundled via webpack, I guess this may be an issue of rollup.

To reproduce, clone https://github.com/leeyeh/rollup-issues then run `npm test`.

```bash
▶ npm test

> rollup-issues@1.0.0 test /Users/leeyeh/work/oss/rollup-issues
> ./test.sh


rollup index.js.
excute bundle.js:
{ for: [Function: for],
  keyFor: [Function: keyFor],
  useSetter: [Function],
  useSimple: [Function] }
[stdin]:980
console.log(_Symbol());
            ^

TypeError: _Symbol is not a function
    at [stdin]:980:13
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:413:34)
    at node.js:289:27
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

rollup index.js with node_modules/** treated external.
excute bundle.external.js:
Treating 'babel-runtime/core-js/symbol' as external dependency
{ [Function]
  for: [Function: for],
  keyFor: [Function: keyFor],
  useSetter: [Function],
  useSimple: [Function] }
Symbol()
```

**Comment by leeyeh** [comment]
Any news here? Is there anything I can do to help?

**Comment by eventualbuddha** [comment]
Sorry for the delay. It looks like [this part is clobbering the real Symbol](https://github.com/zloirock/core-js/blob/60a946b529d29e9a7a9773536c7fd716018de46c/modules/es6.symbol.js#L172-L186), somehow. That's all I could dig up with 15 minutes.

**Comment by leeyeh** [comment]
After upgrading everything to latest, this bug can not be reproduced any more. Thanks for your time @eventualbuddha .
