### ISSUE TITLE
babel plugin appears to have no effect

### ISSUE THREAD

**Issue by travi** [rollup/rollup-plugin-babel#54]
while I'm still debugging on my end, I thought it could be valuable to confirm if there are any high-level details that I'm simply missing. i'm still fairly new to rollup and am currently running it through [grunt-rollup](https://github.com/chrisprice/grunt-rollup), so it is taking me some time to prepare a reduced test case.

my goal is to prepare a bundle from react source that imports css-modules (from `.scss` files in this case) that strips the css-module imports. i have a separate build that treats the css-modules as external for the `browser` main file, but i want them totally removed from the bundle intended for the server side of a universally rendered app.

i'm attempting to use [babel-plugin-transform-require-ignore](https://github.com/morlay/babel-plugin-transform-require-ignore) to strip the `.scss` imports, which works appropriately in other uses.

my `.babelrc` that is working correctly in the other cases:
```json
{
  "presets": [
    "react",
    "es2015"
  ],
  "env": {
    "development": {
      "retainLines": true
    },
    "node": {
      "plugins": [
        [
          "babel-plugin-transform-require-ignore",
          {
            "extensions": [".scss"]
          }
        ]
      ]
    }
  }
}
```

my config within the gruntfile:
```js
es5: {
        options: {
            format: 'cjs',
            sourceMap: true,
            plugins: function () {
                return [
                    babel({
                        babelrc: false,
                        exclude: ['./node_modules/**'],
                        presets: ['react', 'es2015-rollup'],
                        plugins: [
                            ['babel-plugin-transform-require-ignore', {'extensions': ['.scss']}]
                        ]
                    })
                ];
            }
        },
        files: {
            'lib/main.js': 'src/main.js'
        }
    }
```

when i run the grunt task, i get the following error because the import still exists when rollup attempts to build the bundle and it encounters the non-js syntax:
```
Warning: Error loading /path/to/sass/file/_navbar.scss: /path/to/sass/file/_navbar.scss: Unexpected token (1:0) Use --force to continue.
```

is there simply something that i don't understand about how this process should work in this case that you could point me to? otherwise, are there any areas that you would suggest that i target as i try to reduce the test case to narrow in on the problem?

**Comment by eventualbuddha** [comment]
Your rollup config, particularly the `plugins` part, looks incorrect. It should be an array like so:

```js
options: {
  // …
  plugins: [
    babel({
      // …
    })
  ]
}
```

**Comment by Rich-Harris** [comment]
@eventualbuddha I think that might be a grunt-rollup thing...

**Comment by Rich-Harris** [comment]
@travi Ok, so I've just had a look at babel-plugin-transform-require-ignore and it looks like the README is incorrect – it says that it removes `import` statements but [clearly it doesn't](https://github.com/morlay/babel-plugin-transform-require-ignore/blob/master/src/index.js), it only removes `require` calls.

Since your `.babelrc` uses `es2015`, the `import` statement is turned into a `require`, which is why it's behaving as expected outside Rollup. The README also says the project is deprecated, so I probably wouldn't bother trying to raise an issue.

Luckily there's a much easier way to solve this than faffing about with Babel plugins:

```js
options: {
    format: 'cjs',
    sourceMap: true,
    plugins: function () {
        return [
            {
                transform: ( code, id ) => {
                    if ( extname( id ) === '.scss' ) {
                        // return an empty module
                        return { code: '', map: { mappings: '' } };
                    }
                }
            },
            babel({
                babelrc: false,
                exclude: ['./node_modules/**'],
                presets: ['react', 'es2015-rollup']
            })
        ];
    }
}
```

The first 'plugin' will turn `.scss` files into empty modules, so that importing them will have no effect.

**Comment by travi** [comment]
You're right, that's clearly the problem. It's unfortunate that the readme is so blatantly wrong because that certainly wasn't the target of my investigation yet. Thank you for digging in and for such a clear explanation of the difference in context. 

I really appreciate your responsiveness and willingness to be so helpful @Rich-Harris. You not only saved me a ton of time, but also went the extra step to help me understand things more clearly.

The deprecation notice that you mentioned is actually referring to the reason that project exists (the deprecation of `require.extensions`) rather than deprecation of the project itself, unless I'm not spotting what you found. I'll go ahead and log an issue with at least a PR to update that readme. Worst case, the issue might help someone else looking to use that plugin in case they run into a similar issue.

Thanks again!
