### ISSUE TITLE
2.5.1 with rollup@0.26.7 is broken

### ISSUE THREAD

**Issue by scriptype** [rollup/rollup-plugin-babel#61]
We had "SyntaxError: Unexpected token extends" in runtime seemed to be caused by the lack of babelHelpers. Reverted rollup version to `0.26.3` and rollup-plugin-babel to `2.4.0` to fix this. I'm not sure if this have anything with rollup version.

**Comment by tyler-johnson** [comment]
Also seeing this issue. It seems like rollup (or perhaps this plugin) is trimming out the `babelHelpers` variable that the `extends` method was attached to. Now `extends` is declared as a standalone variable causing this error.

Setting `rollup-plugin-babel` back to `2.4.0` did fix the issue for me.

**Comment by Rich-Harris** [comment]
Are you able to try the latest version of Rollup (0.32) and rollup-plugin-babel together? This sounds like the same issue as https://github.com/rollup/rollup-plugin-babel/issues/55, which was fixed in https://github.com/rollup/rollup/pull/696/commits/528b692a38ce06ba753632381ed1b8b647b1936b.
