### ISSUE TITLE
global this transformed to undefined

### ISSUE THREAD

**Issue by Mevrael** [rollup/rollup-plugin-babel#62]
Importing a 3rd party package

```javascript
(function (root) {
   ...
})(this);
```

but babel transforms global this to undefined and I am getting root undefined error in browser and all bundled app is not working.

**Comment by Rich-Harris** [comment]
This is a Babel issue – you need to either a) use whatever combination of plugins and presets achieves the necessary transforms without turning `this` into `undefined`, or b) exclude the third party package from being transformed (unless the 3rd party package is doing things wrong by shipping untranspiled code, this is generally the recommended option).

To do b), your config file would look something like this:

```js
import babel from 'rollup-plugin-babel';

export default {
  entry: 'src/main.js',
  format: 'cjs',
  plugins: [
    babel({
      include: 'src/**' // or `exclude: 'node_modules/**'`
    })
  ]
};
```
