### ISSUE TITLE
Read babel configuration from package.json

### ISSUE THREAD

**Issue by havenchyk** [rollup/rollup-plugin-babel#63]
Hi, in babel's docs I see the option to specify babel config inside package.json.

> You can alternatively choose to specify your .babelrc config from within package.json like so:

```
{
  "name": "my-package",
  "version": "1.0.0",
  "babel": {
    // my babel config here
  }
}
```

Is it possible with this plugin? If not, would like to accept a PR for it?

**Comment by Rich-Harris** [comment]
This should Just Work™ – the plugin doesn't look for a `.babelrc` or `pkg.babel`, that's done by Babel itself. Is it not working for you?

**Comment by havenchyk** [comment]
Yeah, I have tried after I created this issue. Sorry for the noise.
