### ISSUE TITLE
Not working with v2.6

### ISSUE THREAD

**Issue by mcmdhr** [rollup/rollup-plugin-babel#68]
Hello,
I use this plugin with my project named `suanshi`.It has been working fine, but yesterday my friend clone the project  and find it's not working.
After debugging, I thought that's because of `rollup-plugin-babel` version.
My local environment is working now, because  of the `rollup-plugin-babel` version is `v2.4.0`, and my friend's version is `v.2.6.1`.
There is the logic:

``` bash
➜  suanshi git:(master) ✗ cake build
[BABEL] Note: The code generator has deoptimised the styling of "/Users/max/code/suanshi/scripts/../bower_components/viz-components/dist/index.js" as it exceeds the max of "100KB".
{ [SyntaxError: 'import' and 'export' may only appear at the top level (2059:0) in /Users/max/code/suanshi/scripts/../bower_components/viz-components/dist/index.js]
  pos: 176742,
  loc: Position { line: 2059, column: 0 },
  raisedAt: 176748,
  code: 'PARSE_ERROR',
  file: '/Users/max/code/suanshi/scripts/../bower_components/viz-components/dist/index.js' }
```

That's very magical...right?

And there is `rollup-config` file, I have no idea how to fix the error about `v2.6.1`

``` coffeescript
R = 'rollup-plugin'

node = require "#{R}-node-resolve"
babel = require "#{R}-babel"
aliasify = require "./#{R}-alias"
commonjs = require "./#{R}-commonjs"
coffeescript = require "#{R}-coffee-script"

top = "#{__dirname}/.."
lib = "#{top}/lib"

module.exports =
    entry: "#{lib}/index.js"
    plugins: [
        coffeescript()
        babel
            exclude: "#{top}/node_modules/**"
        aliasify
            constants: "#{lib}/constants.js"
            components: "#{top}/bower_components/viz-components/dist/index.min.js"
            util: "#{lib}/util.js"
            settings: "#{lib}/settings.js"
            lodash: "#{lib}/submodules/lodash.js"
        node
            jsnext: true
            main: true
            extensions: ['.js', '.json', '.coffee', '.jsx']
        commonjs
            exclude: ['node_modules/lodash-es/**']
            extensions: ['.js', '.jsx', '.coffee']
    ]

```

**Comment by damountie** [comment]
It looks like [2.6.1 has an error](https://github.com/rollup/rollup-plugin-babel/commits/v2.6.1), so don't worry about trying to fix it yourself. I can't tell you which is the best version for you to use.

**Comment by eventualbuddha** [comment]
Where does `viz-components` come from?

**Comment by mcmdhr** [comment]
@eventualbuddha 
`viz-components` is basic repo for this project, included by `bower`.

**Comment by Rich-Harris** [comment]
I believe this is the same as https://github.com/rollup/rollup-plugin-babel/issues/58 – the solution is to run the `commonjs` plugin *before* `babel`. Tracked at https://github.com/rollup/rollup-plugin-commonjs/issues/146, so I'll close this.
