### ISSUE TITLE
babel support in Electron boilerplate

### ISSUE THREAD

**Issue by mickr** [rollup/rollup-plugin-babel#7]
I am using electron-boilerplate to build an electron app and it includes rollup. I would like to transpile my code with babel but can't seem to get it to work. I have added the plugin and created a babelrc file with the rollup presets but the code still seems to be ES6 code and not transpiled.

Trimmed for brevity
```javascript
var babel = require('rollup-plugin-babel');
var rollup = require('rollup');

var bundle = function (src, dest) {
    var deferred = Q.defer();

    rollup.rollup({
        entry: src,
        plugins: [
            babel()
        ]
    }).then(function (bundle) {
        var jsFile = pathUtil.basename(dest);
        var result = bundle.generate({
            format: 'iife',
            sourceMap: true,
            sourceMapFile: jsFile,
        });
        return Q.all([
            destDir.writeAsync(dest, result.code + '\n//# sourceMappingURL=' + jsFile + '.map'),
            destDir.writeAsync(dest + '.map', result.map.toString()),
        ]);
    }).then(function () {
        deferred.resolve();
    }).catch(function (err) {
        console.error(err);
    });

    return deferred.promise;
};
```

Any help would be appreciated!

Thanks!

**Comment by Rich-Harris** [comment]
That's... odd. Are you able to reproduce it in a repo or gist that you can share? What versions of everything are you using?

**Comment by lukeapage** [comment]
I modified electron-boilerplate to use rollup and it worked fine, I think there is just probably something wrong with your code that is running rollup (like destDir is the wrong place or somesuch)

**Comment by eventualbuddha** [comment]
@mickr did you ever get this sorted out? I'd like to close this if it's been resolved.

**Comment by axelstudios** [comment]
@mickr I hit this exact same thing also while using electron-boilerplate.  Make sure you create the `.babelrc` file:
```json
{
  "presets": ["es2015-rollup"]
}
```

**Comment by mickr** [comment]
I’ll try that, I haven’t had a chance to revisit that project in awhile,
but will give that a try! Close away!
