### ISSUE TITLE
Native modules in babel-preset-es2015

### ISSUE THREAD

**Issue by BarryThePenguin** [rollup/rollup-plugin-babel#70]
In [`babel@6.13.0`](https://github.com/babel/babel/blob/f3ad8a83926787cec3621c532d13abf059a5e8e4/CHANGELOG.md#loose-and-modules-options-for-babel-preset-es2015-3331-3627) you can now pass an options to change the behavior of modules in the es2015 preset

The end result is you can now do the following instead of using the `babel-preset-es2015-rollup` package.

```js
{
  presets: [
    ["es2015", { "modules": false }]
  ]
}
```

I can put together a PR if needed

**Comment by Pauan** [comment]
If this issue is fixed it would also provide a good workaround to issue #71.

**Comment by piuccio** [comment]
isn't this working already?

**Comment by eventualbuddha** [comment]
Yes, this is working. You can either use an updated version of babel-preset-es2015-rollup or use babelrc-rollup.

**Comment by BarryThePenguin** [comment]
Wouldn't it be useful to update the documentation in the readme though?
