### ISSUE TITLE
react preset is not applied to node_modules when jsnext is true

### ISSUE THREAD

**Issue by piuccio** [rollup/rollup-plugin-babel#74]
I know that the title doesn't help, but I've created an example [repo here](https://github.com/piuccio/preact-rollup).

If you use `preact` as alternative to `react` and bundle everything with `jsnext: false` it works just fine.

When you set instead `jsnext: true`, `preact` happens to be an ES6 module, so it has to be converted by babel. I've included it in `include` but the compilation fails because `preact-compat/src/index.js` includes some JSX code.

I don't understand why the JSX in my `index.js` is converted just fine (I'm using `react` preset) while the JSX in `node_modules` isn't.

**Comment by piuccio** [comment]
This PR kinda fix it developit/preact-compat#144 but it's still weird that babel config is not applied on node modules

**Comment by Andarist** [comment]
Closing this as outdated, I hope you have worked around your issue. Feel free to open a new one it stays unresolved.
