### ISSUE TITLE
Cant run in es3 environment because helper code isn't run through es3 transforms.

### ISSUE THREAD

**Issue by fusepilot** [rollup/rollup-plugin-babel#77]
Repro: https://github.com/fusepilot/interop-require-default-repro

With this code:

``` js
function test() {
  Object.assign({}, {foo: 'bar'})
}

test()
```

`output-babel.js` runs fine in an es3 environment.

`output-rollup.js` doesn't, because it contains this chunk of code around line 209:

``` js
var interopRequireDefault = function (obj) {
  return obj && obj.__esModule ? obj : {
    default: obj // this should be 'default': obj
  };
};
```

The helper code added in isn't being passed through either `babel-plugin-transform-es3-member-expression-literals`
or `babel-plugin-transform-es3-property-literals`.

**Comment by Andarist** [comment]
That is because it's generated from rollup itself in the CJS finalizer. If you want to achieve es3 compatibility with this you might want to check if there is rollup option for that or you might raise an issue there. Not much we can do about this one here.
