### ISSUE TITLE
Confused by usage example, example of babel + rollup for the browser

### ISSUE THREAD

**Issue by Loque-** [rollup/rollup-plugin-babel#78]
First of all thank you for the hard work on an excellent project - I am super excited to get these things working so I can be writing best practice JS with modules.

However... I am really struggling to get rollup working with babel - it would be incredibly useful to have an example that _only_ has these elements together building es2015, with the module loader we can't wait to get, for the browser.

There are so many plugins, so many implementation techniques that I am losing hours and now almost days trying to wade through what I should be doing to get these to work (and I am totally on board!). There is a large list of issues I have run into.

I appreciate this might look like a bad request, but I am trying _so_ hard to get this to work and really struggling, I can link my current setup in an effort to reach out for support for my specific case, but I know I am not alone in the struggle to have a bare-bones, babel + rollup config running for es2015 with modules in the browser.

If anyone can help I know it would be appreciated a huge amount.

Many, many thanks again for such an awesome project.

**Comment by Andarist** [comment]
I hope you have got ur setup working by now. You might read about simple rollup+babel setup [here](https://developers.livechatinc.com/blog/how-to-create-javascript-libraries-in-2018-part-1/) - if any other example is needed, let me know and I'll try to provide one.
