### ISSUE TITLE
Is .babelrc being preferred over options passed to plugin?

### ISSUE THREAD

**Issue by Wedvich** [rollup/rollup-plugin-babel#80]
I'm having some trouble getting Rollup and the Babel plugin to play nice.

I have this in my `.babelrc` file:
```json
{
  "presets": ["es2015"]
}
```

And in my Rollup config:

```js
...
plugins: [babel({ presets: [['es2015', { modules: false }]] })]
...
```

If I move the `modules: false` part to my `.babelrc` file, Rollup is happy, but my unit tests fail (they're being passed through `babel-core` and run by Mocha). If I move it to the Rollup config, Mocha is happy, but Rollup gives me the following error:

> Error transforming C:\blabla.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information

So, what's happening here? Am I passing invalid options to the plugin? Is the `.babelrc`  configuration overriding whatever I pass to the plugin? Is it simply not possible to specify this option at all in the plugin?

**Comment by TrySound** [comment]
Use `babelrc: false` option in plugin

**Comment by Wedvich** [comment]
Worked like a charm, thanks! :+1:

**Comment by crobinson42** [comment]
> `babelrc: false`

@TrySound That should be in the DOCS - head banger, I tell you!

**Comment by TrySound** [comment]
@crobinson42 PR welcome.
