### ISSUE TITLE
`Generates sourcemap by default` spec failing

### ISSUE THREAD

**Issue by snuggs** [rollup/rollup-plugin-babel#81]
## Description

On Jun. 6th 2016 @Rich-Harris dependency bumped `source-map` package from _0.5.3 → 0.5.6_. 
https://github.com/rollup/rollup-plugin-babel/commit/6192dc21efdf58eab7cf2c82d79e985a89d3569a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L47

This included a regression failure corrected by _Mozilla_ in the _0.5.6_ release. 
https://github.com/mozilla/source-map/pull/236

In particular the following diff:
https://github.com/mozilla/source-map/pull/236/files#diff-72d90d7b160cfdc50eee99b2a33c871cL320

Which fixed a regression failure of the following bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=889492
## Expected Behavior

Sourcemap name resolution regression fix.
Test suite success. 14 passing, 0 failing
## Current Behavior

null name expectation.
Test suite failure. 13 passing, 1 failing
## Possible Solution
1. 🔧 **change test to reconcile dependency bump of `source-map@0.5.6`**
2. ~~retrograde to `source-map@0.5.3`~~
3. `¯\_(ツ)_/¯
## Steps to Reproduce (for bugs)

`$ npm install && npm test` Results in the following test failure.
https://github.com/rollup/rollup-plugin-babel/blob/master/test/test.js#L104

![capture d ecran 2016-08-31 a 05 33 22](https://cloud.githubusercontent.com/assets/38223/18123535/45a11f20-6f3c-11e6-963a-312891e4faed.png)
### Full Stack Trace

```
13 passing (1s)
  1 failing

  1) rollup-plugin-babel generates sourcemap by default:

      AssertionError: { source: '/Users/rashaunstovall/rollup-plugin-babel/test/samples/class/main.js',
  line: 3,
  column: 10,
  name: 'log' } deepEqual { source: '/Users/rashaunstovall/rollup-plugin-babel/test/samples/class/main.js',
  line: 3,
  column: 10,
  name: null }
      + expected - actual

       {
         "column": 10
         "line": 3
      -  "name": "log"
      +  "name": [null]
         "source": "/Users/rashaunstovall/rollup-plugin-babel/test/samples/class/main.js"
       }

      at test/test.js:116:11

npm ERR! Test failed.  See above for more details.
```
## Your Environment

- Version used: `$ npm --version # 3.8.3` &  `$ node --version # v5.10.1`
- Operating System and version (desktop or mobile): OSX

**Comment by snuggs** [comment]
I believe this was fixed in a recent PR. Possibly in Rollup. @Rich-Harris can you confirm? If so i'll close.

**Comment by Rich-Harris** [comment]
closing now that #82 was merged – thanks
