### ISSUE TITLE
Source map post-generation

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup-plugin-babel#9]
My idea is inheritance and overriding some methods in `babel-core` and `babel-generator` to replace `transformed.map` property with function which will generate source map when we need.

For now we need to add some simple tests about source maps.

**Comment by Rich-Harris** [comment]
This sounds... dangerous :warning: 

I'd be very hesitant to add any functionality that relied on knowing (and monkey patching) the internals of another library. I've just done some quick testing and it looks like the overhead of generating sourcemaps automatically is negligible, so I think it makes more sense to default to always generating sourcemaps.

**Comment by TrySound** [comment]
@Rich-Harris Okay :) But it's not dangerous because babel classes is public api.

**Comment by Rich-Harris** [comment]
I've released 2.1.0 which generates sourcemaps by default. Will do the same for other plugins as and when I get to them
