### ISSUE TITLE
fails when using moduleName option for transform-runtime

### ISSUE THREAD

**Issue by sheerun** [rollup/rollup-plugin-babel#95]
[react-app](https://github.com/facebookincubator/create-react-app/blob/master/packages/babel-preset-react-app/index.js) is using custom option for transform-runtime, like follows:

```
moduleName: path.dirname(require.resolve('babel-runtime/package'))
```

It results in following fragment in transcompiled code:

```
import _classCallCheck from "/Users/sheerun/Source/Hyper/worker/node_modules/babel-runtime/helpers/classCallCheck";
```

but you detection code checks for:

```
import _classCallCheck from "babel-runtime
```

It makes your plugin fail with following message: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!

**Comment by Rich-Harris** [comment]
Fixed in 2.7.1 – thanks
